### ISSUE TITLE
Update the Buffer Exchange framework

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#115]
### Subject
Please let me know your thoughts and suggestions on how this capability could be improved. 

### Environment
* Version of LPub3D - 2.3.1
* Operating system - All

### Solution
TBD

**Comment by jacovandermolen** [comment]
Parts used in the buffer that float in one step should not be counted again or shown in the PLI (and BOM) of the next step. Either I still do something wrong, or it is a bug?

Second wish is the addition of arrows in LPub. Now I use MLCad arrows to show where the floating part(s) have to go, but it would be great to be able to add arrows in LPub3D. These are sharper.
Should be able to specify color and line with and arrowhead shape and size. Nice to have is an arrow with pointer segments and even curved lines?

Third wish is buffer exchange over more then one step. You now can achieve this with the remove group meta that uses MLCad Groups. But it would be nice to indicate bricks in a certain step that are replaced in more then one step later.

Last I never understood why Buffer Exchange can have more letters then A. What is the use of the A in BUFEXCHG A STORE / BUFEXCHG A RETRIEVE and other letters?

**Comment by Landcross** [comment]
I've written a bit about this a little while back: https://github.com/trevorsandy/lpub3d/issues/43
As I wrote in there, In my opinion the two biggest improvements should be:

- A buffer exchange END tag so that if I want a part to 'buffer' in multiple steps I don't have to constantly store and retrieve every step but I can just store it in step 4 and retrieve it in step 8 for example.
- A feature that automatically ignores parts in the PLI within the buffer retrieve

Furthermore, another cool addition would be to be able to retrieve buffers within submodels from the parent (or even further up in the tree) models. A common example would be Technic models were you add those 'pins with bush' only halfway on a submodel, then put the submodel on the mainmodel and push the pins all the way to lock the models together (if that description makes sense ;) ). But this is a nice to have feature and I can imagine that it's more difficult to implement than the above things.

If you could implement the first feature I mentioned above within the next ~4 weeks I would be so incredible thankful. I have to use A LOT of buffer exchange soon (well, part of the reason that it's a lot of buffer exchange is the lack of that feature :P) and that alone would make my life so much better. Is there a donate button somewhere?

PS: I'll get back to you about the assembly positioning issue later today. Didn't had any time last couple of days.

@jacovandermolen Why it can have more letters is indeed a bit useless with the current implementation of buffer-exchange. But if it would be possible to carry a buffer over multiple steps, then having multiple letters (or names) would become much more useful I think.

**Comment by trevorsandy** [comment]
@jacovandermolen,

> Second wish is the addition of arrows in LPub. Now I use MLCad arrows to show where the floating part(s) have to go, but it would be great to be able to add arrows in LPub3D. These are sharper.
Should be able to specify color and line with an arrowhead shape and size. Nice to have is an arrow with pointer segments and even curved lines?

This request does not look like it is related to the Buffer Exchange functionality. However, to achieve a better looking pointer, perhaps you could consider creating a set of 'pointer' part files.

Cheers,

**Comment by jacovandermolen** [comment]
I have these helper files or I use MLCad arrows. However, they do not render that good. No anti-alias lines. The LPub3D arrows are vector based, right? So in a PDF, these are much sharper, especially when it comes to printing instructions. See the attached PDF and image.
[minifig-BI.pdf](https://github.com/trevorsandy/lpub3d/files/2449394/minifig-BI.pdf)
[arrow](https://user-images.githubusercontent.com/32261647/46522739-e438d180-c883-11e8-9ce5-76d455ac46ea.png)

**Comment by Landcross** [comment]
The advantage of arrow-parts over LPub arrows is that actual parts can be positioned in 3D instead of 2D. For example, I regularly show arrows going through Technic holes to indicate where a technic pin or axle has to go. It would not be possible for LPub arrows to go through technic holes.

I think the reason the arrow parts are not anti-aliased is because I believe LDView only applies AA on LDraw edges. Because those helper parts are real simple LDraw parts, they don't have any edges.

**Comment by jacovandermolen** [comment]
Ah, yes. Agreed. That would be a disadvantage.
Perhaps I can create lines around the helper arrows.

However it still would be nice to be able to freely add arrows ;-)
To indicated to push or draw attention to a certain situation in the model.

**Comment by jacovandermolen** [comment]
Now why haven't I thought of this before?
Compare helper arrow with and without lines:
![afbeelding](https://user-images.githubusercontent.com/32261647/46523914-81e1d000-c887-11e8-9744-6eb3137612ec.png)

**Comment by jacovandermolen** [comment]
Working on some instructions I finally figured out the use of another letter than A for buffer exchange.
Furthermore, I figured out multi-step buffer exchange, where your store the A buffer in a step and retrieve it 2 or more steps later.
When done, I will share the instructions, file, and explanation.

**Comment by trevorsandy** [comment]
Excellent! Many thanks.

Cheers,

**Comment by trevorsandy** [comment]
> I figured out multi-step buffer exchange, where your store the A buffer in a step and retrieve it 2 or more steps later.
When done, I will share the instructions, file, and explanation.

Hi Jaco - can you share the meta command configuration to achieve this behaviour ? Many thanks.

Cheers,

**Comment by riazanovskiy** [comment]
Another common use case for "remove parts from submodel" functionality mentioned by @jacovandermolen would be wires and tubes. They can have default placement in the submodel instructions and then they are placed correctly in the main model.

**Comment by trevorsandy** [comment]
@riazanovskiy Thank you to "Quote" the "mention" you are referring to so it is a bit more efficient to understand your point. Also, it would be better to have an illustration of the use case - you are very good at providing excellent illustrations.

**Comment by riazanovskiy** [comment]
(I'm not very good at reading irony as English is not my first language so please if you think there's something wrong with my comments say it straight up and I'll try to correct it)

I was referring to this part

> Furthermore, another cool addition would be to be able to retrieve buffers within submodels from the parent (or even further up in the tree) models. A common example would be Technic models were you add those 'pins with bush' only halfway on a submodel, then put the submodel on the mainmodel and push the pins all the way to lock the models together (if that description makes sense ;) ). But this is a nice to have feature and I can imagine that it's more difficult to implement than the above things.

An example would be any instruction which introduces a motor or a pneumatic hose as a submodel. For instance, look at this [instruction](https://www.lego.com/biassets/bi/6064360.pdf) for 41999 set. On page 77 it a shows subassembly with an L motor with some cable placement. On the following page the cable placement is different.
Or for a more recent example see this 42082 [instruction](https://www.lego.com/biassets/bi/6245458.pdf). On pages 72-73 it shows a submodel with a motor and later, on page 82, the cable is connected to the battery box (compare pages 80 and 82).

Similar for pneumatic hoses, [see](https://www.lego.com/biassets/bi/6245455.pdf) set 42080. Page 19 shows a submodel with a hose and on pages 130-131 the hose assumes new shape.

**Comment by trevorsandy** [comment]
There is nothing wrong with your comments. I could not find any reference to the _”remove parts from submodel”_ mention you are referring to in...

> Another common use case for "remove parts from submodel" functionality mentioned by @jacovandermolen

...so I asked that you provide a quote to help me better understand the context and use case you are describing.

Furthermore, there is certainly no irony in my remark about the quality of the tickets you have created - they are usually excellent in describing the behaviour you are experiencing.

Cheers,

**Comment by trevorsandy** [comment]
For those following this ticket, please turn your attention to #411 for further details. 

I’ve finally completed my interpretation of the expectations captured in this ticket inLPub3D v2.4. The new behaviour is titled Build Modifications - implying the modification of a build step to display a pertinent nuance in the build procedure. 

Details of this expansive new feature are captured in ticket #146 

Cheers,
