### ISSUE TITLE
Convert submodel to callout generates the wrong pointer meta

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#137]
### Subject
Convert submodel to callout generates the wrong pointer meta

### Environment
* Version of LPub3D - 2.3.2
* Operating system - Windows 10, Processor Architecture (x86_64)

### Steps to reproduce
Reaching a submodel choose to convert to callout.

### Expected behavior
The arrow meta should be correct

### Actual behavior
The pointer meta is wrong:
0 !LPUB CALLOUT POINTER CENTER 0 _nan nan_ 0 0 0 0 0 0 1

### Workaround
Delete the line manually and add a pointer to callout manually

**Comment by trevorsandy** [comment]
Hi Jaco, what do you mean by 'wrong' ponter meta - precisely what is wrong ? Can you elaborate on point 'The arrow meta should be correct' - 'correct' in what way ? 

`0 !LPUB CALLOUT POINTER CENTER 0 nan nan 0 0 0 0 0 0 1`

I don't see what is wrong with this meta command. Keep in mind that the pointer arrow meta has changed since 2.2 with the introduction of multi-segment pointers which allow up to 3 segments in your pointer stem. 

The additional 0s compared to, let's say LPub3D 2.2.2, are the default values for the pointer's segments. Automatically generated pointer meta does include the full meta format; however, as you indicated in your workaround suggestion, the parse engine will still accept the legacy (short) meta format.

You can see in the image below, both auto-generated and manually created meta commands.

![screenshot - 23_10_2018 23_44_28](https://user-images.githubusercontent.com/13388970/47392766-cd1c2f80-d71d-11e8-9514-ab9933e5ae97.png)

Cheers,

**Comment by jacovandermolen** [comment]
The nan nan is not right is it?
Anyway after covert to callout, I get a blank screen. Only navigating a
page back or forward gives met the opportunity to remove the pointer meta
line. Then going to the page with the callout I can add a pointer again
which gives me correct meta.
Op di 23 okt. 2018 om 23:46 schreef Trevor SANDY <notifications@github.com>

**Comment by trevorsandy** [comment]
Ok, I thought the Nan Nan was a redaction. I can’t reproduce this behaviour. Could you send an example model file that does ?
