### ISSUE TITLE
v2.3.3 - MacOS Sierra (10.12.6) - 3rd Party Renderers

### ISSUE THREAD

**Issue by trdoolan** [trevorsandy/lpub3d#146]
### Subject
3rd Party Renderers are not producing any images, and are generating errors relating to PLI move permissions.

### Environment
* Version of LPub3D - see Help->About LPub3D
v2.3.3
* Operating system - OS Name, Processor Architecture (x86,x86_64)
MacOS Sierra 10.12.6 Macbook Pro mid-2012, 8Gb RAM, Intel Core i7

### Configuration
* LPub3D installation path
  **- macOS: `/Applications/LPub3D.app`**
  
* Application data path
  **- macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`**

* Registry Extract
  - macOS: ` ~/Library/Preferences/com.lpub3d-software.LPub3D.plist`

* Renderer configuration files
  - `[Application data path]/ldv/ldvPOV.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.3/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
LDView will occasionally produce PLI errors like the POVRay errors, but most often just produces a blank page as per capture.

Provide a sample mpd/ldr file that reproduces the problem.
File used for reproducing error included (Delta7 v1.6.22-release.ldr)

### Expected behaviour
Previous versions rendered parts and model stage and displayed them on the page. I was expecting the same to occur.

### Actual behaviour
Behaviour of each renderer captured and attached.

### Workaround
None so far. Only the Native renderer works, but produces images of far lower quality than v2.0/LDView combination that was previously installed. I've also tried removing the 'LPub3D folder under the Model location so that the temp files and output are recreated, but this also results in LDView PLI move errors similar to what happens with POV-Ray. The LDR files in " 'model-path'/LPub3D/tmp" are being updated (date/time stamp confirms this), but no files are appearing in either 'assem' or 'parts', nor are the files in 'viewer' being updated. There are no png files in any of these folders, and I would expect there would be something (from previous version behaviour)

### Solution suggestion
Unknown. I have considered folder/file permissions at the CLI, but the permissions are all set as (RWX, R-X, R-X for User/Group/All) and installation occurred under login that has administrative privileges.
I had thought to change the binary location for LDView to a separate discrete install on the system already, but cannot change this in Preferences and a suitable console based text editor is not installed to edit any settings files.
Brew has been installed, with required libraries updated/installed prior to LPub3D being installed. LibPNG is updated/reinstalled as per instructed

[LPubTicket.zip](https://github.com/trevorsandy/lpub3d/files/2523622/LPubTicket.zip)

**Comment by trevorsandy** [comment]
Many thanks for sharing the details of your unexpected behaviour.

After reviewing your logs, It looks like there are 2 items to address:

1. Your `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini` file is empty as it was not written from the template on initial application startup -  (ticket #141 corrects this behaviour). The LDGLite abnormal end may have occurred because arguments (`-i2 -J -q -2g,2x`) from the INI file were not received.  You can see this in the `stdout-ldglite `log `Arguments = ...` line:
```
LDGLite Version 1.3.4 (64bit)      
====================
Arguments = /Applications/LPub3D.app/Contents/3rdParty/ldglite-1.3/bin/ldglite -ca0.01 -cg0,0,4285419 -v1753,1240 -o0,-206 -W1 -fh -mF/Users/troy/Google Drive/Lego/03. MOCs & MODs/0003. MOD-001 - 10215 UCS ObiWan Jedi Starfighter (Delta7)/04. Instruction Development/v1.6.22-release/LPub3D/assem/10215 delta7 ucs mod_v1_1_0_0_0_1_0_0_0_1_10_1753_150_DPI_1_0.01_23_45.png /Users/troy/Google Drive/Lego/03. MOCs & MODs/0003. MOD-001 - 10215 UCS ObiWan Jedi Starfighter (Delta7)/04. Instruction Development/v1.6.22-release/LPub3D/tmp/csi.ldr 
FOV = 0.01
FROM = (0, 0, 4.28542e+06)
LDraw LDConfig = /Applications/Studio 2.0 Beta/ldraw/LDConfig.ldr
Znear, Zfar = 4.28242e+06, 4.28842e+06
CAM = (0, 0, 4.28542e+06)
Rendering OffScreen
Using GL Pixel Format Attributes for OSX/SDK 10.8 or later

OpenGL Driver Info
====================
GL_VENDOR = NVIDIA Corporation
GL_VERSION = 2.1 NVIDIA-10.17.5 355.10.05.45f01
GL_RENDERER = NVIDIA GeForce GT 650M OpenGL Engine
GL_SHADING_LANGUAGE_VERSION = 1.20
```
The **immediate LDGLite workaround** is to manually update the LDGLite INI file contents. You can do this either by copying `/Applications/LPub3D.app/Contents/Resources/ldglite.ini` to `/Applications/LPub3D.app/Contents/3rdParty/ldglite-1.3/config/ldglite.ini` or opening and pasting the content using LPub3D Configuration menu and the attached ldglite.ini.
[ldglite.zip](https://github.com/trevorsandy/lpub3d/files/2525060/ldglite.zip)

2. Your `stderr-ldview` log contains the following return:
```
dyld: Library not loaded: /opt/X11/lib/libOSMesa.8.dylib
  Referenced from: /Applications/LPub3D.app/Contents/3rdParty/ldview-4.3/bin/LDView
  Reason: image not found
```
**Note:** Since version 2.1.0, all renderers are compiled and bundled with LPub3D - see the [README.txt](https://trevorsandy.github.io/lpub3d/assets/docs/lpub3d/README.txt) for details. The bundled instance of LDView is a command console only version of the application that uses OSMesa from the X11 library. This is a material difference From LPub3D 2.0 which used the 'installed' instance of LDView, LDGLite and POV-Ray.

This stderr return above usually means the required dynamic library is either not found where LPub3D expects it to be or it is not installed.

The **immediate LDView workaround** for the latter, is to install [XQuartz](https://www.xquartz.org/). For the former, you can employ these steps from this excellent post: [Fixing dyld image not found on Mac OS](http://droolfactory.blogspot.com/2012/07/fixing-dyld-image-not-found-on-mac-os.html).

Let me know if you are able to progress after addressing these items.

Cheers,

**Comment by trevorsandy** [comment]
Hi Troy. Excellent.

Cheers,
