### ISSUE TITLE
Group removed inside a callout still visible on the main model

### ISSUE THREAD

**Issue by zero0n3** [trevorsandy/lpub3d#158]
### Subject
Group removed inside a callout still visible on the main model

### Environment
* Version of LPub3D - 2.3.3 build 1024
* Operating system - Windows 7 64bit / MacOs Mojave 10.14

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3
  - macOS: `/Applications/LPub3D.app`
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
  - macOS: `~/Library/Application Support/LPub3D Software/LPub3D/`

### Steps to reproduce
You can open directly attached ldr file. There are 3 pages:
the first with the "main model"
in the second page you can see the callout with 4 steps where the fourth step is the one containing the **REMOVE GROUP command that works correctly at this time**
The third page contain the submodel attached to the main model and where you can see the bug about showing again the removed group and the new group.

### Expected behaviour
I would like to not see in the main model step, where the callout is placed, the removed group inside callout.

### Workaround
Using the buffer exchange inside callout to remove the group of parts

[removegroup sample.zip](https://github.com/trevorsandy/lpub3d/files/2572270/removegroup.sample.zip)

**Comment by Landcross** [comment]
Just wanted to report that I came across this same issue today. Was able to work around it by duplicating the submodel and removing the removed group in there and then doing the same remove group in the parent model. I think that sentence makes little sense...

In any case, I can confirm this is an issue (though not sure if it's an actual bug or more a limitation of the META command).

**Comment by trevorsandy** [comment]
Corrected.

This was and old LPub bug: 
![screenshot - 02_12_2018 05_58_25](https://user-images.githubusercontent.com/13388970/49335898-55340580-f5f7-11e8-8ae7-e64f54d6d7b6.png)

The problem was in the routine that write submodels to the tmp folder. The intention is to remove groups, parts and names, where defined for removal, from submodels (e.g. callout.ldr) before writing the ldr to the tmp folder; however, while the functionality to detect remove group metas was implemented, the functionality to populate the csi file with group metas (e.g. 0 MLCAD BTG A) so the preceding part line can be removed was not. As a result, part lines following group metas were not removed from submodels as expected. This behaviour has been corrected.

![screenshot - 02_12_2018 05_51_29](https://user-images.githubusercontent.com/13388970/49335959-c32cfc80-f5f8-11e8-86a5-257da46cac22.png)

![screenshot - 02_12_2018 05_51_40](https://user-images.githubusercontent.com/13388970/49335960-c32cfc80-f5f8-11e8-97af-70e0b380a3ed.png)

![screenshot - 02_12_2018 05_52_01](https://user-images.githubusercontent.com/13388970/49335961-c32cfc80-f5f8-11e8-9e22-5b38ef25a145.png)

Cheers,
