### ISSUE TITLE
AppStream XML is broken

### ISSUE THREAD

**Issue by probonopd** [trevorsandy/lpub3d#20]
The AppStream XML in the AppImage is broken:

```
    <release version="2.1.0.770" date="2018-02-02"
```

Notice the missing closing `>`.

Reference:
https://github.com/AppImage/appimage.github.io/pull/355

**Comment by trevorsandy** [comment]
Good catch - Thanks! Fixed.

The culprit was lpub3d.appdata.xml. Correction should be in 774

**Comment by probonopd** [comment]
Thanks for the fix, please ping me when a new release is out so that I can re-run the test in AppImageHub.

**Comment by trevorsandy** [comment]
v2.1.0 released.

**Comment by probonopd** [comment]
https://download.opensuse.org/repositories/home:/trevorsandy/AppImage/LPub3D-latest-x86_64.AppImage still seems to have unparseable XML.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/342528210#L622

**Comment by probonopd** [comment]
Same for https://github.com/trevorsandy/lpub3d/releases/download/v2.1.0/LPub3D-2.1.0.0.775_20180213-x86_64.AppImage.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/342531164#L638

**Comment by trevorsandy** [comment]
Yep - I confirm line 2 in [lpub3d.appdata.xml](https://github.com/trevorsandy/lpub3d/blob/master/mainApp/lpub3d.appdata.xml) was malformatted. 

It is   ​
`<!-- Copyright 2018 Trevor SANDY <trevor.sandy@gmail.com> -->`, 

but it should be  
`<!-- Copyright 2018 Trevor SANDY &lt;trevor.sandy&amp;gmail.com&gt; -->`

There was also another invisible character issue that I could not find - so I rebuilt the file manually. It seems to parse properly now. I'll post an updated build shortly - waiting on SoruceForge.net to come back up (they're having some issues after migrating to a new DC).

My CI builds do not perform this check. What is the command to test the appdata.xml file ?
Here is my Travis AppImage Code:
```
qmake -makefile -nocache QMAKE_STRIP=: CONFIG+=release CONFIG-=debug_and_release CONFIG+=api;
make -j$(nproc);
make INSTALL_ROOT=$AppImageBuildPath -j$(nproc) install;
[ ! -e linuxdeployqt-continuous-x86_64.AppImage ] && \
wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
renderers=$(find $AppImageBuildPath/opt -type f);
for r in $renderers; do executables="$executables -executable=$r"; done;
unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
export VERSION="$LP3D_VERSION"    # linuxdeployqt uses this for naming the file
./linuxdeployqt-continuous-x86_64.AppImage $AppImageBuildPath/usr/share/applications/*.desktop $executables -bundle-non-qt-libs -verbose=2 > CreateAppImage.log 2>&1;
./linuxdeployqt-continuous-x86_64.AppImage $AppImageBuildPath/usr/share/applications/*.desktop -appimage -verbose=2 >> CreateAppImage.log 2>&1;
```
And you can see here my OBS [appimage.yml](https://github.com/trevorsandy/lpub3d/blob/master/builds/linux/obs/alldeps/appimage.yml) file

Here is the [CreateAppImage.log](https://github.com/trevorsandy/lpub3d/files/1733217/CreateAppImage.log).

Thanks,

**Comment by probonopd** [comment]
If `appstreamcli` is installed, then it should be invoked by `appimagetool` automatically. But beware, the version of `appstreamcli` that comes with distributions is utterly outdated in most cases and may give false alarms.

**Comment by probonopd** [comment]
Triggered a re-run of the test: https://travis-ci.org/AppImage/appimage.github.io/builds/345597276

**Comment by trevorsandy** [comment]
On OBS, this appdata scheme is completely inconsistent!
No matter what I try, validation across x86 and ARM AppImage builds fail.
On Ubuntu (Travis CI) there is no evidence of validation but builds are successful.
On OBS  x86_64 builds, validation is reported as successful but there is also a message
stating no appstream meta info was found. On ARM builds validation fails with
invalid tag 'launchable' - this tag is valid. I spent 2 days on this and zero.
I give up!

**Comment by probonopd** [comment]
cc @ximion. We need to do something so that people can use AppStream easily.

**Comment by ximion** [comment]
Like, not build on ancient distributions? ;-)
For Ubuntu, there is a [PPA](https://launchpad.net/~ximion/+archive/ubuntu/appstream), but one will need at least Ubuntu 18.04 (a recent GLib is absolutely required).
As for this particular issue, you can run `xmllint` with the appropriate options on metainfo files unconditionally. That will ensure that at least the XML is valid and readable.

**Comment by probonopd** [comment]
@ximion in order to achieve compatibility with all still-supported LTS releases, we are building most AppImages on Ubuntu 14.04 trusty (at this point in time the oldest still-supported LTS release). It would make like much easier if all developers of third-party applications would take care not to introduce build-time dependencies that make it hard to impossible to build software for still-supported LTS releases. I am a bit at a loss what I can do. If I remove AppStream linting, then I foresee most AppStream files to be broken. But I don't know a better way to do AppStream linting than to use the version of appstreamcli that runs on the oldest still-supported LTS release. Any ideas highly appreciated.

@trevorsandy thanks for your patience and for pointing out this issue. Indeed we need to find a solution. I am sorry for the trouble you were going through.

**Comment by trevorsandy** [comment]
@probonopd @ximion the XML is valid and readable - this I confirmed before commit.

Without implicating the appstream scheme, my builds are successful, I opted to include the appdata.xml in response to the message: 
```
[ 2434s] WARNING: AppStream upstream metadata is missing, please consider creating it
[ 2434s]          in usr/share/metainfo/lpub3d.appdata.xml
[ 2434s]          Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
[ 2434s]          for more information or use the generator at http://output.jsbin.com/qoqukof.
```
Following the guidance of this message (i.e. respecting specs from www.freedesktop or using a template appdata.xml generated from qouqkof) does NOT provide an appdata file that will pass the `appstreamcli` validation - particularly on the `AppImage.arm` build. This is the frustrating part; the `AppImage` build succeeds as described above but the ARM build fails with the following scenarios. Builds are using openSUSE Leap 42.2 (x86_64, ARM). 
 
Fail scenarios against the above criteria include the , component `<id>` not respecting a reverse DNS format such as `org.trevorsany.lpub3d.desktop`. If you leave out `.desktop`, the build fails with message the id is not the same as the desktop file as so no desktop file of that name exist. However, using the reverse DNS name format then generates an error that basically states there must be a desktop file of the same name format based on "the latest spec". However, adding the .desktop file  `org.trevorsany.lpub3d.desktop` (copying to root and renaming the `lpub3d.desktop`, then referencing this file in the `linuxdeployqt` call) generates the error that the .desktop file was not found. Actually renaming the original desktop file to use the reverse DNS name then breaks the AppImage build process itself as it states it cannot find the .desktop file - even though the .desktop file in referenced in the call.

As you can see, the fail scenarios simply make it impossible to include the appimage.xml file on OBS and result with a successful build across both x86 and ARM builds. x86 alone can be successful however; while on Travis CI's Ubuntu Trusty, AppImage builds always succeed no matter what appdata configuration is used - but this is probably because I do not explicitly call the `appstreamcli` in my shell script.
