### ISSUE TITLE
Only one single submodel picture is shown cross all submodels

### ISSUE THREAD

**Issue by swl2019** [trevorsandy/lpub3d#208]
### Subject
Only one single submodel picture is shown cross all submodels 

### Environment
* LPub3D 2.3.6 Revision 0 Build 1101 Hash g1c651eab 
* Windows 10, 64-bit,

### Configuration
see attachements

### Logs
see Attachements - amended with comments showing the steps 1) - 4) lined up below

### Screenshots
see attachements

### Steps to reproduce
1) open file - re-rendering is triggered - submodel image in page 1 is correct
2) go to page 3 - page rendering is triggered - wrong submodel Image (of page 1) is shown
3) force re-rendering via Ctrl+R - correct submodel Image is shown
4) go to page 1 back - page shows the wrong submodel image of page 3

### Expected behaviour
each submodel should show ist own submaodel image

### Actual behaviour
the last rendered submodel Image is shown in every submodel Image. 
a re-rendering via Ctrl-R creates for each submodel (despite the page or model) always a named "01_@display_0_1753_150_dpi_0.5_0.01_23_-45.png" - however the content of the image is changing in respect to the page the Ctrl-R is pressed

### Workaround
none

### Solution suggestion
None

### Attachements

Step 1) Page 1 CORRECT submodel image
![GBC Marble Run BVB v11-06_page_1_CORRECT_submodel_image](https://user-images.githubusercontent.com/48833324/54833444-6ac05e80-4cbe-11e9-9e14-b725272485ef.jpg)

Step 2) Page 3 WRONG submodel image
![GBC Marble Run BVB v11-06_page_3_WRONG_submodel_image](https://user-images.githubusercontent.com/48833324/54833437-6a27c800-4cbe-11e9-8bf5-e3f812a4b11d.jpg)

Step 3) Page 3 CORRECT submodel Image after re-rendering via Ctrl-R
![GBC Marble Run BVB v11-06_page_3_CORRECT_submodel_image](https://user-images.githubusercontent.com/48833324/54833436-698f3180-4cbe-11e9-989e-4d28bc903d37.jpg)

Step 4) Page 1 WRONG submodel image
![GBC Marble Run BVB v11-06_page_1_WRONG_submodel_image](https://user-images.githubusercontent.com/48833324/54833445-6b58f500-4cbe-11e9-9f58-7047e7346c76.jpg)

[LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/2997122/LPub3DLog.txt)

[GBC Marble Run BVB v11-06.zip](https://github.com/trevorsandy/lpub3d/files/2998264/GBC.Marble.Run.BVB.v11-06.zip)

Configuration 
![Configuration-Preferences-General](https://user-images.githubusercontent.com/48833324/54833438-6a27c800-4cbe-11e9-89fc-9d589055b665.JPG)
![Configuration-Preferences-Other](https://user-images.githubusercontent.com/48833324/54833440-6ac05e80-4cbe-11e9-95a8-5853cc244ebf.JPG)
![Configuration-Preferences-Publishing](https://user-images.githubusercontent.com/48833324/54833441-6ac05e80-4cbe-11e9-8536-a69f36d97380.JPG)
![Configuration-Preferences-Rendering](https://user-images.githubusercontent.com/48833324/54833442-6ac05e80-4cbe-11e9-9c0a-728d30f8a4b4.JPG)
![Configuration-Preferences-Theme+Logging](https://user-images.githubusercontent.com/48833324/54833443-6ac05e80-4cbe-11e9-9de5-bccbde746f4a.JPG)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
The behaviour you are experiencing is caused by your submodel naming convention. For example, the baseName for `01.ball_mover01.connection_rod` is interpreted by Qt (the LPub3D development toolkit) as `01` because the baseName() function captures the full name's characters up to the first point `.` for the base name.

The base name is used as a prefix for the submodel image name. As the captured value is `01` and there are multiple submodels starting with 01, the defined image name is the same for all submodels starting with 01, 02 etc... This means your submodel images are overwritten leaving only the last generated image available.

The behaviour you describe is produced by these underlying anomalies.

### Solution

I will take a look at addressing this naming exception; however, you might want to consider revising your naming convention. To immediately treat the unexpected behaviour, you could change the `.` in your naning to `_`. You could also follow the LDraw naming format which uses the .ldr extension for submodel file name. 

Cheers,

**Comment by trevorsandy** [comment]
Addressed.

I've updated the image name creation routine to look for and truncate the .`ldr`, .`dat`, or .`mpd `file extension. If these extensions are not found,  use the entire submodel file name.

Cheers,

**Comment by swl2019** [comment]
Travor,

thank you for the quick reply. I successfully applied the change of "." to "_".

Best Regards
