### ISSUE TITLE
Native PLI image render failed.

### ISSUE THREAD

**Issue by scumpy0815** [trevorsandy/lpub3d#214]
### Subject
When opening my test.ldr with faded steps and a motor, I get the attached errors and the program closes.

### Environment
* Version of LPub3D - 2.3.7.0.1195
* Operating system - Windows 10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path C:\LDraw\LPub3D
* Application data path %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\
* Renderer configuration files

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`   not existing
* Renderer Log: `[LDraw model path]/stdout-povray`   not existing
* Renderer Log: `[LDraw model path]/stderr-ldglite`   not existing
* Renderer Log: `[LDraw model path]/stderr-povray`   not existing

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Tell me how to reproduce this issue.
Provide a sample mpd/ldr file that reproduces the problem.

### Expected behaviour
The file should be opened and ready for use.

### Actual behaviour
Errors and a closed program.

### Workaround
found nothing

### Solution suggestion

[Test.zip](https://github.com/trevorsandy/lpub3d/files/3024066/Test.zip)

**Comment by trevorsandy** [comment]
The logs show the returned messages stem from the generated PLI image not having any opaque content - basically it an empty image 0x0 pixels. It's a bit strange because your 'Fade Percent' setting appear to be set to 0 - fully opaque. If you wish to fade previous steps, the fade percent should be greater than 0. In my test illustrated below, I'm using 50 percent.

Unfortunately, I cannot reproduce the behaviour you are reporting in my environment.

Here are my executed steps and results:

![Screenshot - 05_04_2019 , 07_04_26](https://user-images.githubusercontent.com/13388970/55666742-62862880-5853-11e9-8d2a-9b057c95fa82.png)
![Screenshot - 06_04_2019 , 10_24_08](https://user-images.githubusercontent.com/13388970/55666950-26a09280-5856-11e9-9533-b33b25b78d4b.png)
![Screenshot - 05_04_2019 , 07_06_09](https://user-images.githubusercontent.com/13388970/55666743-62862880-5853-11e9-887c-f3ab4e3f2084.png)
![Screenshot - 05_04_2019 , 07_06_27](https://user-images.githubusercontent.com/13388970/55666744-62862880-5853-11e9-8546-40b92d09e234.png)
![Screenshot - 05_04_2019 , 07_06_58](https://user-images.githubusercontent.com/13388970/55666745-62862880-5853-11e9-9cff-d74b41665ff6.png)
![Screenshot - 05_04_2019 , 07_07_18](https://user-images.githubusercontent.com/13388970/55666746-631ebf00-5853-11e9-9542-9fab3244056c.png)
![Screenshot - 05_04_2019 , 07_07_35](https://user-images.githubusercontent.com/13388970/55666748-631ebf00-5853-11e9-8b2b-74da5bfca1ac.png)
![Screenshot - 05_04_2019 , 07_07_57](https://user-images.githubusercontent.com/13388970/55666749-631ebf00-5853-11e9-86bb-fc6b1aa349f9.png)
![Screenshot - 05_04_2019 , 07_08_15](https://user-images.githubusercontent.com/13388970/55666750-631ebf00-5853-11e9-9ec1-b0d55418be60.png)
![Screenshot - 05_04_2019 , 07_09_05](https://user-images.githubusercontent.com/13388970/55666751-63b75580-5853-11e9-811d-324fa55ee15d.png)

Perhaps you could try set the preferred renderer to LDView to test if there is a change in the behaviour.

Cheers,

**Comment by scumpy0815** [comment]
If I change the fade percentage, the error is still there. Only changing the renderer to LDView helps. There I can use my 0 % fade.

**Comment by scumpy0815** [comment]
The problem seems to be gone in 2.3.8

**Comment by scumpy0815** [comment]
The problem seems to be gone in 2.3.8
