### ISSUE TITLE
Metacommands are ignored since 2.3.7

### ISSUE THREAD

**Issue by 6638** [trevorsandy/lpub3d#227]
### Subject
Metacommands are ignored since 2.3.7. In 2.3.6 (installed) the problem didn't occur.

### Environment
2.3.7 (installed, portable), 2.3.8 (installed, portable)
Windows 7 x64

### Configuration
The problem is independent of a selected renderer. 

### Screenshots
page_1.png
<img width="620" alt="page_1" src="https://user-images.githubusercontent.com/49516540/55971152-361e4200-5c81-11e9-9d25-cdaccc70306e.png">

### Steps to reproduce
Tried to shrank the file to a minimum:

0 FILE main.ldr
0 SAMPLE
0 Author: 6638
0 !LPUB SUBMODEL_DISPLAY SHOW GLOBAL TRUE
1 16 -90 -9.5 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 NOFILE
0
0 FILE subModel-1.ldr
0 Author: 6638
0 !LPUB PLI PLACEMENT LOCAL RIGHT TOP SUBMODEL_DISPLAY OUTSIDE
0 !LPUB ASSEM PLACEMENT LOCAL BOTTOM_RIGHT PAGE INSIDE -0.1 -0.1
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 NOFILE

### Expected behaviour
Positioning of PLI and assembly to respect the metacommands.

### Actual behaviour
Positioning of PLI and assembly ignores metacommands.

### Workaround
None found.

### Solution suggestion
Some bug introduced since 2.3.7?

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
The unexpected behaviour is because your model file sample does not produce a step number. In other words there is only one step. The default placement for a submodel is to the right of the step number. 

![Screenshot - 14_04_2019 , 07_48_22](https://user-images.githubusercontent.com/13388970/56088950-f9259b80-5e8a-11e9-992c-15dc0b4d1cb0.png)

As not step number exist, the actual placement is undefined so attempting to place the PLI relative to the submodel is yielding unpredictable behaviour.

I'll take a look at adding some exception handling for this scenario although I believe the likelihood of this occurring in instructions, outside of testing, is quite rare.

Here are the results for 2.3.8 with and without more than one step:
![Screenshot - 14_04_2019 , 07_44_13](https://user-images.githubusercontent.com/13388970/56088956-1eb2a500-5e8b-11e9-94bd-03b4e5b564a3.png)
v2.3.8 did not like the extraneous offset values ( -0.1 -0.1) at the end of the ASSEM PLACEMENT meta
![Screenshot - 14_04_2019 , 07_43_51](https://user-images.githubusercontent.com/13388970/56088959-21ad9580-5e8b-11e9-9d4d-21322fbf4c67.png)
![Screenshot - 14_04_2019 , 08_02_48](https://user-images.githubusercontent.com/13388970/56088994-cb8d2200-5e8b-11e9-9a5a-65c88fb1b144.png)

And the results for 2.3.6:
![Screenshot - 14_04_2019 , 07_37_55](https://user-images.githubusercontent.com/13388970/56088963-28d4a380-5e8b-11e9-80c5-e29ab938db13.png)
![Screenshot - 14_04_2019 , 07_38_33](https://user-images.githubusercontent.com/13388970/56088960-26724980-5e8b-11e9-9164-080519a47580.png)

Cheers,

**Comment by trevorsandy** [comment]
I’m changing this ticket to a “change” as the solution is to add logic to handle positioning content relative to a display submodel when the submodel is not positioned relative to a step number.

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

Thank you for having a look on it.

1. Is it wrong to use negative offsets? I use them very intensively.
2. Even if to remove negative offsets and to add steps, positioning is still invalid. Let's create such a file:

0 FILE main.ldr
0 !LPUB PLI PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
0 !LPUB STEP_NUMBER PLACEMENT GLOBAL BOTTOM LEFT PLI OUTSIDE
0 !LPUB SUBMODEL_DISPLAY PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
0 !LPUB SUBMODEL_DISPLAY SHOW GLOBAL TRUE
1 16 -90 -9.5 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 STEP
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 NOFILE
0
0 FILE subModel-1.ldr
0 !LPUB PLI PLACEMENT LOCAL RIGHT TOP SUBMODEL_DISPLAY OUTSIDE
0 !LPUB ASSEM PLACEMENT LOCAL BOTTOM_RIGHT PAGE INSIDE
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 STEP
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 NOFILE


Step 1: Wrong positioning of the PLI and the step number.
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/49516540/56098330-b05bfa00-5eff-11e9-8494-889d942f432d.png">

Step 2: Wrong positioning of the step number.
<img width="960" alt="p2" src="https://user-images.githubusercontent.com/49516540/56098332-b94ccb80-5eff-11e9-8776-3dfcae45947c.png">

Step 4: Wrong positioning of the PLI and the step number.
<img width="960" alt="p4" src="https://user-images.githubusercontent.com/49516540/56098334-beaa1600-5eff-11e9-9cb2-9f651d35e1ab.png">

**Comment by trevorsandy** [comment]
I've added a small update to better manage when both Submodel and PLI are placed relative to Step Number. However, this update does not address the multitude of permutations possible when placing items relative to each other and it does not resolve the cases, like those listed here, when some of those permutations produce unexpected results. Considering the status, I will leave this ticket open.

Cheers,

**Comment by trevorsandy** [comment]
I believe I have corrected the placement routines to process all the cases presented in this ticket.

Here are the results for the sample model fils specified:

```
0 FILE main.ldr
0 SAMPLE
0 Author: 6638
0 !LPUB SUBMODEL_DISPLAY SHOW GLOBAL TRUE
1 16 -90 -9.5 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 NOFILE
0
0 FILE subModel-1.ldr
0 Author: 6638
0 !LPUB PLI PLACEMENT LOCAL RIGHT TOP SUBMODEL_DISPLAY OUTSIDE
0 !LPUB ASSEM PLACEMENT LOCAL BOTTOM_RIGHT PAGE INSIDE -0.1 -0.1
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 NOFILE
```

![Screenshot - 23_04_2019 , 11_02_37](https://user-images.githubusercontent.com/13388970/56568456-58845980-65b7-11e9-84b0-8427004ca383.png)

```
0 FILE main.ldr
0 !LPUB PLI PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
0 !LPUB STEP_NUMBER PLACEMENT GLOBAL BOTTOM LEFT PLI OUTSIDE
0 !LPUB SUBMODEL_DISPLAY PLACEMENT GLOBAL TOP_LEFT PAGE INSIDE
0 !LPUB SUBMODEL_DISPLAY SHOW GLOBAL TRUE
1 16 -90 -9.5 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 STEP
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 NOFILE
0
0 FILE subModel-1.ldr
0 !LPUB PLI PLACEMENT LOCAL RIGHT TOP SUBMODEL_DISPLAY OUTSIDE
0 !LPUB ASSEM PLACEMENT LOCAL BOTTOM_RIGHT PAGE INSIDE
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 STEP
1 71 0 0 0 0 0 1 0 1 0 -1 0 0 64179.dat
0 NOFILE
```
![Screenshot - 23_04_2019 , 11_06_00](https://user-images.githubusercontent.com/13388970/56568686-d0528400-65b7-11e9-880d-4ffba5832c11.png)

Cheers,

**Comment by 6638** [comment]
Hello, Trevor.

I appreciate your time to fix it very much. Now, I finally upgraded from the version 2.3.6.

Cheers!
