### ISSUE TITLE
Installation impossible if uninstallation is impossible

### ISSUE THREAD

**Issue by Scharnvirk** [trevorsandy/lpub3d#240]
### Subject
Installation is impossible if the uninstaller does not work.

For some reason, I get following message during uninstallation:
"There is no installation of LPub3D 2.3.9 Rev 0 Build 1228 ."

This by itself is not a big deal.

However each next installation fails, because it calls uninstaller first, which fails - which also stops the installation process.

### Environment
* Version of LPub3D - LPub3D 2.3.9.0.1228 (18 04 2019 04:05:08) 
* Operating system - Windows 10 64

### Configuration
* LPub3D installation path
  - Windows: `D:\lego\ldraw\LPub3D` [x86_64]
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry Extract
  - Windows (installed): https://drive.google.com/open?id=1xojKNOwZdlKx93h1e7klqEeAFNJj22fs
* Renderer configuration files - are these relevant?

### Logs
* Application Log: None, I disabled all logs due to performance reasons

### Steps to reproduce
Very easy. Rename uninstall.exe on existing LPub3D install to something else and run next installer.

### Expected behaviour
Installation should give the user an option to continue. After all, reinstallation may be a caused by user who has broken something which cannot be easily fixed.

### Actual behaviour
The installer stops with uninstallation error.

### Workaround
Use a registry cleaning tool, probably, to trick the installer into thinking that there is no existing install. I try not to touch registry unless REALLY necessary though, so untested.

### Solution suggestion
Show a warning with a checkbox for optional continue with re-writing existing settings if such an error happens.

**Comment by trevorsandy** [comment]
The behaviour as described is as designed. LPub3D will only call the uninstall module if it detects a registry entry for an existing installation. In such a situation, the install program is designed to terminate the installation process, if the uninstall process cannot be invoked or fails to complete. Overriding this behaviour is not a good solution because it will lead to LPub3D being installed on top of another installation.

If an existing installation has been modified (or prematurely aborted) so that it creates a situation where LPub3D cannot successfully complete the uninstall process. Correcting the installation so it can be successfully uninstalled by LPub3D, uninstalling the installation from 'Add or remove programs' or manually removing the installation are the options available to the user. LPub3D will not override the fact that it failed to uninstall an existing installation and; therefore, continue the installation.

However, I understand your request is to add functionality that prompts the user to allow LPub3D to override the failed attempt to remove an existing installation and continue to remove the installation - e.g. delete the existing installation and user data folders if they exist and remove any implicated registry entries - and proceed with a fresh install. 

Cheers,

**Comment by Scharnvirk** [comment]
Thanks for detailed reply. 

From the user's perspective, unless he is an advanced one, there is no real fix for this when this happens, aside from reinstalling system. The user may even not know about such thing as registry, newer windows versions are pretty stable and do not require such haxes.

Solution which basically alters uninstaller to truly uninstall everything is a good one, because it solves the problem. Then this bug would not be an installer bug like I described it but an uninstaller bug.

A side-note question, if I may. Is there a channel to contact you and ask some questions, better than github? These are not really "issues" but questions of advanced yet undocumented features (like adding user-made parts to the library).

**Comment by trevorsandy** [comment]
I've added a function to the install script that prompts the user to 'force' an uninstall when the uninstall.exe execution. This override prompt is specific to the scenario where the uninstall.exe execution command returns a failure status. Other failure errors will continue to behave as before this update.

**Note: All components of LPub3D are uninstalled** if this option is accepted.

![Screenshot - 08_05_2019 , 16_54_32](https://user-images.githubusercontent.com/13388970/57386604-fc275980-71b4-11e9-985c-2072b00c1f25.png)

![Screenshot - 08_05_2019 , 16_55_02](https://user-images.githubusercontent.com/13388970/57386606-fc275980-71b4-11e9-9285-787f7c9d873a.png)

Cheers,
