### ISSUE TITLE
Autoupdate not working: unsupported 16-Bit application

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#261]
### Subject
"A new version of LPub3D is available! Click OK to download it now" -> "OK" -> "To install the update, LPub3D will quit. Click OK to begin installing the LPub3D update" -> "OK" 
then message appears 
![image](https://user-images.githubusercontent.com/11013917/57949377-e0c2f980-78ec-11e9-87e3-4548c16b90b6.png)

### Environment and configuration
Same as in #258 
LPub3D is installed manually, not with LDrawAllInOneInstaller

**Comment by riazanovskiy** [comment]
Also the uninstaller does not work. 
I downloaded the new release from Github Releases, the installer tried to uninstall previous version 
![изображение](https://user-images.githubusercontent.com/11013917/57949904-5bd8df80-78ee-11e9-8f4b-4cff49fecf91.png)
It also cannot be uninstalled manually (with the same message).

Can I do anything else to help to reproduce the problem?

Many thanks for your work on LPub3D!

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

The Windows installer distribution contains both x64 and x32 platform installations. On the surface, it looks like the platforms were not successfully packaged. However the packaging log did not show any anomalies.

Regarding the message “There is no installation of LPub3D 2.3.10...” there should be a message prompt to continue as shown in #240.

If you are unable to progress with the Windows installer, you can download a portable distribution from the GitHub repository instead. 

I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Another thought on the “Unsupported 16-bit” message, perhaps the installer was not completely downloaded.

Cheers,

**Comment by trevorsandy** [comment]
I've updated the install script to take into account the KO uninstall executable and repackaged the Windows installer. On failure to execute the uninstaller, you will be prompted to completely remove the existing installation as described in #240. You can download the updated installer from GitHub or SourceForge.

Something is wrong with the auto-update downloader routine as it reports complete without downloading the distribution. It's a bit strange because the same routine is working as expected to download the LDraw archive libraries.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

See #266 for details

Cheers,
