### ISSUE TITLE
Segfault in Native renderer

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#273]
### Subject
If I open file with Native renderer, following error message is shown and LPub crashes with a segfault

![Screenshot_2019-05-24_18-06-43](https://user-images.githubusercontent.com/11013917/58337561-bb833d80-7e4e-11e9-984e-1ffa0d363a3e.png)

Work OK under LDView renderer

### Environment and configuration
LPub3D 2.3.11 under Arch Linux

### Logs
https://gist.github.com/riazanovskiy/6c953aff6251b6e6a8ed09b58316530a

### Steps to reproduce
[mack.mpd](https://github.com/trevorsandy/lpub3d/files/3217493/mack.mpd.txt)

This issue look similar to #214 but I don't think the file uses any opaque parts

**Comment by riazanovskiy** [comment]
Reproduces on Windows 10 (the program also crashes)

**Comment by trevorsandy** [comment]
This behaviour was corrected in #272.

Basically, the Native renderer (based on LeoCAD) requires the submodel to be inlined; otherwise, it is not found. While submodel inlining is automatically performed for CSI assemblies, it was not implemented for PLI parts. However, with the new LPub3D capability that supports customized LDCad generated parts which places the 'fallback' LDraw content in a separate submodel, it is now necessary to inline the PLI model file to successfully render the generated part. 

I can confirm that in LPub3D v2.3.11, this scenario causes and abnormal end because the Native renderer cannot locate the PLI part's submodel.

With the enhancement in place, the generated part loads as expected.

![Screenshot - 25_05_2019 , 08_36_05](https://user-images.githubusercontent.com/13388970/58366361-6a685d80-7ed1-11e9-9dae-e19aa2170e7b.png)

Cheers,
