### ISSUE TITLE
Image is cropped when ASSEM PLACEMENT is used

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#274]
This is not a obvious bug, maybe I just didn't figure out the right command.

### Subject
Suppose I want to show some place in more detail. I'd like to move it to the centre of the page and perhaps enlarge it (if I'm not mistaken I can use Scale parameter for LDView, Camera distance for Native renderer and FOV angle for both). But the image is cropped accoring to it's original placement.

Screenshot for LDView renderer:
![image](https://user-images.githubusercontent.com/11013917/58339610-9f819b00-7e52-11e9-97de-50f8b81b8164.png)

Screenshot for Native renderer:
![image](https://user-images.githubusercontent.com/11013917/58339837-1dde3d00-7e53-11e9-8786-3af8d9d9aa91.png)

### Environment and configuration
LPub3D 2.3.11 under Windows 10

### Steps to reproduce
File
```
0 Author: LDraw
1 1 0 -16 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 160 -40 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 340 -16 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 520 -40 -80 1 0 0 0 1 0 0 0 1 3006.dat
1 1 660 -16 -80 1 0 0 0 1 0 0 0 1 3006.dat
0 STEP
0 !LPUB ASSEM PLACEMENT LOCAL CENTER PAGE INSIDE -0.7 0
1 4 720 -40 -90 0 0 -1 0 1 0 1 0 0 3002.dat
```

### Expected behaviour
I suppose this is "behaviour as designed". Or is it a bug? Anyway, what is the official way to do this?

**Comment by trevorsandy** [comment]
If you are using the Native renderer the default camera distance is -260. Negative values zoom out and positive ones zoom in. So to zoom in enter a positive value - I use 110 below. The default placement for an Assy is the center of the page so the placement meta you specified does not have any effect. 

See the following shots that illustrate zooming in using the camera distance factor.

I am using perspective projection - set under LPub3D Preferences
![Screenshot - 25_05_2019 , 10_04_42](https://user-images.githubusercontent.com/13388970/58366861-920ef400-7ed8-11e9-94f9-151ce7e293b8.png)

perspective projection is also set under 3DViewer Preferences
![Screenshot - 25_05_2019 , 10_07_28](https://user-images.githubusercontent.com/13388970/58366863-96d3a800-7ed8-11e9-97da-15f7e121d48d.png)

Context menu
![Screenshot - 25_05_2019 , 10_05_21](https://user-images.githubusercontent.com/13388970/58366891-d5696280-7ed8-11e9-81ed-b7f9d12eb5a3.png)

Camera distance factor dialogue
![Screenshot - 25_05_2019 , 10_26_51](https://user-images.githubusercontent.com/13388970/58366892-d5696280-7ed8-11e9-8d02-56815335b119.png)

Result
![Screenshot - 25_05_2019 , 10_27_13](https://user-images.githubusercontent.com/13388970/58366893-d601f900-7ed8-11e9-892a-f72fb8f631d0.png)

**Note:** I noticed that the Native camera distance dialogue validator is not correctly set. It shows a default value of 100 which is the validator minimum - it should actually show -250 as that is the correct default value. If you want to enter 100 you will have to enter a value other than 100 so that the dialogue records a change. If 100 is presented and you select ok, the dialogue will not take any action as no modification has occurred. This anomaly has been corrected for the next release (v2.3.12).

Cheers,
