### ISSUE TITLE
Sub-model in separate file not being included

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#279]
### Subject
When a sub-model is contained in a separate file to the main file, no instructions for the sub-model are being generated.

The LDraw standard (https://www.ldraw.org/article/218) specifies that for a linetype of 1, a subfile can be located in a number of different locations:

> Sub-files can be located in the LDRAW\PARTS sub-directory, the LDRAW\P sub-directory, the LDRAW\MODELS sub-directory, the current file's directory, a path relative to one of these directories, or a full path may be specified.

### Environment
* Version of LPub3D - 2.3.11.0.1269 (17 05 2019 13:24:45)
* Operating system - Windows 10, x86_64

### Configuration
* LPub3D installation path
  - N/A
* Application data path
  - N/A
* Registry Extract
  - N/A
* Renderer configuration files
  - N/A

### Logs
N/A

### Screenshots
Refer to pdf within the attached zip file.

### Steps to reproduce
[mils_foundation.zip](https://github.com/trevorsandy/lpub3d/files/3243310/mils_foundation.zip)

1. Extract the two mpd files from within the zip file
2. Open the file mils_track_double_plain_vanilla.mpd using LPub3D
3. The first page is generated as a blank page

### Expected behaviour
The steps within the mils_foundation.mpd file should appears as steps within the instructions

### Actual behaviour
The first page is generated as a blank page

### Workaround
None.

### Solution suggestion
LPub3D should search for files in all locations as per the LDraw standard;
- LDRAW\PARTS sub-directory
- the LDRAW\P sub-directory
- the LDRAW\MODELS sub-directory
- the current file's directory
- a path relative to one of these directories
- a full path

**Comment by trevorsandy** [comment]
Thanks for reporting this behaviour. This enhancement is already in the queue.

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

David, the example model file you provided was quite helpful to ensure valid exceptions are handled. 

In fact, your file has a common MPD inconsistency that is mostly benign when all subfile references are contained within the same document. I'll explain...

The name of the external subfile `mils_foundation.mpd` is  different from its `FILE <model>` meta `0 FILE 000-00-main.ldr`. However, you specify the name of the subfile in the main model file subfile reference `1 4 0 0 0 1 0 0 0 1 0 0 0 1 mils_foundation.mpd`. This is a contravention of the LDraw MPD META Statement specification:

~~~
FILE

Format: 0 FILE <model>

Where:
<model> is the name of the following LDraw file.
~~~

As you can imagine, the problem with this configuration, is LPub3D will look for the subfile reference but not find it because no content will exist under that `FILE <model>`. The content for `mils_foundation.mpd` is placed under the '000-00-main.ldr' `FILE <model>`. Consequently, a missing part error condition will be triggered for subfile reference `mils_foundation.mpd` - see #275. 

It's already a contradiction to specify an external subfile as an MPD subfile reference because, by definition, an MPD reference is contained within the main model document. The configuration is further deteriorated when the subfile name is different from the `FILE <model>` meta.

As you have duplicated the MPD subfiles `000-10-baseplate.ldr` and `000-20-corner_identifier.ldr` so they appear in both the main MPD `mils_track_double_plain_vanilla.mpd` and the subfile reference `mils_foundation.mpd`, this content is successfully rendered for step 1. However, the callout formatting and added parts specified in `mils_foundation.mpd` is not detected because no MPD `FILE <model>` meta with that name is specified anywhere. 

LDrawfiles load result for example model files as is.
![Screenshot - 04_06_2019 , 03_46_34](https://user-images.githubusercontent.com/13388970/58850457-e2cbdd00-868e-11e9-966a-729e30b119d9.png)

Step 1 display for example model file as is. 
![Screenshot - 04_06_2019 , 03_48_11](https://user-images.githubusercontent.com/13388970/58850479-f9723400-868e-11e9-8340-04c28a1eda8e.png)

Step 1 display for example model files after changing `FILE <model>` meta `0 FILE 000-00-main.ldr` in  `mils_foundation.mpd` to `0 FILE mils_foundation.mpd`
![Screenshot - 03_06_2019 , 17_47_02](https://user-images.githubusercontent.com/13388970/58850552-4229ed00-868f-11e9-9226-df9a31f93c3a.png)

You can see the exception behaviour quite well in the logged trace.
![Screenshot - 04_06_2019 , 04_58_18](https://user-images.githubusercontent.com/13388970/58850675-e3b13e80-868f-11e9-9193-99ccbde95afa.png)
![Screenshot - 04_06_2019 , 04_57_07](https://user-images.githubusercontent.com/13388970/58850680-e744c580-868f-11e9-9154-085fa2135c91.png)

Cheers,

**Comment by d-j-m-0** [comment]
Hi Trevor,

Thanks for the explanation. However, I believe there's still an itch to scratch.

I modified the content of the mils_foundation.mpd file to ensure the FILE (and Name:) metacommands aligned with the file name. I also cleaned up the mils_track_double_plain_vanilla.mpd file (which had some unreferenced leftovers in it, though not the 000-10-baseplate.ldr and 000-20-corner_identifier.ldr you suggested). 

I then did a clean start of LPub3D on the amended mils_track_double_plain_vanilla.mpd file (with the amended mils_foundation.mpd file in the same directory). The PDF that is generated still contains an empty first page instead of pages for the step-by-step instructions for mils_foundation.mpd.

I'm not convinced that this:

> It's already a contradiction to specify an external subfile as an MPD subfile reference because, by definition, an MPD reference is contained within the main model document. The configuration is further deteriorated when the subfile name is different from the FILE <model> meta.

is correct. The LDraw [File Format standard](https://www.ldraw.org/article/218.html) states that an Ldraw file can have an ldr, dat or mpd extension. A line type 1 can reference any sub-file and must be a valid Ldraw file name. Ergo, I believe an MPD can validly refer to another MPD as a sub-file. Both LDview and LDCad successfully open and display mils_track_double_plain_vanilla.mpd with the contents of mils_foundation.mpd displayed as expected.

Aside from the cleansed mpd files, I've also included the LPub3D log file plus stderr and stdout in the zip file. If I look at the content of the Lpub3DLog.txt file, it seems to suggest it is searching for mils_foundation.mpd in the LPub3D archives but not in the current directory. ... Or have I still got this wrong?

Regards,

David

[mils_v2.zip](https://github.com/trevorsandy/lpub3d/files/3251292/mils_v2.zip)

**Comment by d-j-m-0** [comment]
Ah, does your comment "Implemented" actually mean it has been added to version 2.3.12 and I just need to be a bit patient :)

David

**Comment by trevorsandy** [comment]
Yes it does.

Cheers,

**Comment by trevorsandy** [comment]
> The LDraw File Format standard states that an Ldraw file can have an ldr, dat or mpd extension. A line type 1 can reference any sub-file and must be a valid Ldraw file name. Ergo, I believe an MPD can validly refer to another MPD as a sub-file. Both LDview and LDCad successfully open and display 

Don't confuse the file extension with the logic intended for files with said extension. There is a specific purpose for MPD files defined as:

> MPD files or "Multi-Part Documents" are a way to combine several LDraw files into one consolidated source. This allows for ease in posting or emailing a model made up of many subparts.

The logic to enable the MPD specification is powered by the `FILE <model>` and `NOFILE` meta commands, which essentially expects submodel (not parts) subfiles specified at the top-level to be 'consolidated' within the top-level model file. If a submodel subfile reference is an external MPD file, the file name must match the `<model>` designation if you reference the submodel subfile using the file name instead of the `<model>` designation.

As an example, if you remove the  `FILE <model>` meta command from `mils_track_double_plain_vanilla.ldr`,  it will be treated as an LDR file and will load  `mils_foundation.mpd` without issue as there is no expectation that `mils_foundation.mpd` must be a consolidated `<model>` designation. Instead, `mils_foundation.mpd` is treated as just another external (LDR/part) reference. Of course, when  `mils_foundation.mpd` is loaded, as it is an MPD file, any submodel subfile references will be expected to be specified as a `FILE <model>` meta.

As a test, if you open the test file in LeoCAD, you will also notice there is no reference of the submodel `mils_foundation.mpd`. 

Cheers,
