### ISSUE TITLE
Fonts in generated instruction depend on system DPI setting

### ISSUE THREAD

**Issue by riazanovskiy** [trevorsandy/lpub3d#292]
### Subject
Although #267 is fixed, LPub output still depends on system DPI setting. For instance, the first page was generated with 100% scaling 
![instruction-lpub_page_103](https://user-images.githubusercontent.com/11013917/59966323-a10eb380-9523-11e9-83b2-6a85224abb0b.png)
and the second one was generated with 175% scaling
![instruction-lpub_page_103-dpi175](https://user-images.githubusercontent.com/11013917/59966327-b4218380-9523-11e9-8eb8-17c84a996af1.png)

LPub is a kind of compiler, its output should only depend on mpd source file (and LPub configuration files), not on system scaling setting, which is supposed to affect only UI elements
![image](https://user-images.githubusercontent.com/11013917/59966340-06fb3b00-9524-11e9-8912-5e56a5ae1848.png)

### Environment
LPub 2.3.12 under Windows 10

### Workaround
Right now I switch scaling to 100%, generate PDF with LPub, and look through it while fixing the instruction in LPub with scaling switched back to 175% (otherwise the interface elements are too small for me to read). This workflow is rather slow.

It is also possible to manually set the step number font settings to counter the scaling change.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

Indeed, there is more to be done to make the LPub3D generated content completely autonomous from the system DPI scaling as I have indicated in my last #267 comment.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

Going back to #267...

> I compute the style rect scale ratio by dividing the system DPI against the constant of 96 DPI.

However, this is not enough...

> I noticed there are several other fixed-size items that will have to be manually scaled - notably the page background, and CSI image. The scene ruler should also be adjusted. So there is more to be done...

Qt uses the DPI settings in several other places to determine the size metrics (e.g. in layouts, to determine spacing around items and the like). Consequently, I have decided to force Qt to ignore completely the OS DPI settings and default to 96 fake-DPIs everywhere by doing:

`QApplication::setAttribute(Qt::AA_Use96Dpi);`

before instantiating the QApplication. 

`Qt::AA_Use96Dpi` will...

> Assume the screen has a resolution of 96 DPI rather than using the OS-provided resolution. This will cause font rendering to be consistent in pixels-per-point across devices rather than defining 1 point as 1/72 inch.

Consequently, I rolled back setting the style rect size using the 'dpiRatio()' implemented in #267. 

Do not hesitate if you encounter any unexpected behaviour caused by this correction.

Here is a shot of the UI at 175% scale on Windows.

![Screenshot - 28_06_2019 , 04_04_58](https://user-images.githubusercontent.com/13388970/60312488-ca807280-995b-11e9-899f-11c8491415e0.png)

...and at 100%

![Screenshot - 28_06_2019 , 04_00_46](https://user-images.githubusercontent.com/13388970/60312556-087d9680-995c-11e9-8293-a7436731e930.png)

Cheers,

**Comment by riazanovskiy** [comment]
Sorry, I could not verify it is working :/

Should I enable something? 
I downloaded CI build (windows portable x86_64 zip) from this commit https://github.com/trevorsandy/lpub3d-ci/commit/e8ffed5d98b9c262c26dfdbae0fd5e05e1530c47
and got different images and 100% and 175% scaling

![instruction-lpub_page_3-100](https://user-images.githubusercontent.com/11013917/60397336-b05db480-9b54-11e9-9fbf-3716f8c22687.png)
![instruction-lpub_page_3-175](https://user-images.githubusercontent.com/11013917/60397337-b0f64b00-9b54-11e9-9d73-50525a57317f.png)

**Comment by trevorsandy** [comment]
I imagine there must be settings other than 'Scale and Layout' contributing to this behaviour. On my Windows 10 environment, the behaviour is as illustrated above. For me, there is no change in the annotation text font at scale above 100% so I'm not sure what else to look at.

Cheers,

**Comment by riazanovskiy** [comment]
Could you please tell if the file you use to get the screenshots above had 
```
0 !LPUB RESOLUTION GLOBAL ??? DPI
```
line? And if not, which is your default setting? Maybe those are deduces differently on my machine and on yours

**Comment by trevorsandy** [comment]
I used [this model file](https://github.com/trevorsandy/lpub3d/issues/299#issuecomment-507043822) for the shots above. It did not have the `0 !LPUB RESOLUTION GLOBAL ??? DPI` meta command.

Cheers,

**Comment by riazanovskiy** [comment]
And what is your default LPub DPI setting here?

![image](https://user-images.githubusercontent.com/11013917/60426029-75af5700-9bfc-11e9-8d60-10bad71e94c4.png)

> so I'm not sure what else to look at

My hypothesis is that this value might differ

**Comment by trevorsandy** [comment]
I used the default setting - 150 DPI - just as you show in the shot.

Cheers,
