### ISSUE TITLE
Issue: Can't select callout pointers under certain conditions

### ISSUE THREAD

**Issue by TrueMylenium** [trevorsandy/lpub3d#315]
Some individual callout pointers' points can't be selected if multiple pointers exist that share the same placement attributes. E.g. if multiple pointers are set to originate with a BOTTOM attribute and the one with the outermost bounding box has been selected, no other pointers can be selected and the current one stays selected. The user has to go one page forward or back to deselect everything and gain access to the other pointers again for interactive dragging.

Steps:

1. Open test file.
2. Edit Callout pointers as described.

Actual Result:

Pointers remain uneditable under certain conditions.

Expected result:

Pointers remain selectable and editable all the time.

Tech Info:

v2.3.12, Build 1356, 64 bit, Windows 10

Comment:

See Issue #309 for test file you can use. Likely hit testing/ drawing order related.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
> Some individual callout pointers' points can't be selected if multiple pointers exist that share the same placement attributes.

Following your guidance, I an not able to solicit this behaviour. Perhaps, there is some nuance I’m failing to appreciate. Nevertheless, I’ve performed som updates to the base pointer item that should present:
- enhanced grabber behaviour, toggle on on first click of pointer and off on next click, on on subsequent click and so on...
- Fix add Callout pointer malformed (hidden behind Callout) in some cases where the Callout includes a divider. 
- Callout pointer base and tip follow the parent/destination when either is dragged. Before #269, pointer tips would follow but the pointer base would not, after this ticker, the base would follow but the tip was now broken. Both tip and base are now behaving as expected.

Feel free to let me know if these updates positively impact the behaviour you are experiencing.

Cheers,

**Comment by TrueMylenium** [comment]
Well, you're not going to see anything with straight pointers most of the time, of course. Just for kicks try to add extra segments and then have fun picking the angled segments...

**Comment by TrueMylenium** [comment]
Here's some inspiration for you:

![Angled_Pointers](https://user-images.githubusercontent.com/52353330/62350031-c4088c00-b501-11e9-8727-8366a7e5cb7a.jpg)

Try to get a similar arrangement without going bonkers and having to jump across pages just to deselect stuff...

**Comment by trevorsandy** [comment]
Ah, got it. For your sample model, you must manipulate the pointer segments that will create the inner bounding rectangle first then move to the pointer segment(s) that will create the outer. Alternatively, let's say you wanted to extend the first pointer in your model - looking from left to right. As you can see, the first pointer is completely encompassed by the second pointer's bounding rect. The trick is to click on the second pointer tip (the lower, longer one) and drag it back until the first tip is ahead and; therefore, outside the second pointer's bounding rect. Once you've made your adjustment to the first pointer, you can replace the second pointer tip to its original location. 

The current behaviour stems from the way the Qt dev env manages graphic items that are grouped - e.g. my pointers. The grouped items are parented by a group item with its bounding rect stacked in the order of last manipulated group - i.e. pointer. 

I started ticket #244 "send to back" to address this behaviour but there's a lot of effort to get all the graphic items to play nice so I've sort of lowered the priority on this one for the moment. Perhaps, I should take another look at finishing it sooner rather than later.

Cheers,

**Comment by trevorsandy** [comment]
Corrected.

It is now possible to select a pointer completely encompassed by another's bounding rectangle. Additionally, I've completed the first pass for #244.

Cheers,
