### ISSUE TITLE
Problems with PLI annotation

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#353]
### Subject
Various problems with PLI annotation

### Environment
* Version of LPub3D -2.3.13/1511
* Operating system - Win10/64

I got several little issues with PLI annotations (and similar in BOM):
- Default size of box and font are OK for single digit annotations, but 2 digits (long axle or beams) do not fit.
- So I tried to change font size in parts list setup / annotations, but it didn't seem to change anything.
- So I right click on the offending annotations to change font size, it worked but... I had to do that for each and every submodel AND for round and square box style annotations...
I'll email you a link to the model / BI files

**Comment by trevorsandy** [comment]
Hi Philo,

Thank you for reporting this behaviour. 

> Default size of box and font are OK for single digit annotations, but 2 digits (long axle or beams) do not fit.

> So I tried to change font size in parts list setup / annotations, but it didn't seem to change anything.

This is unexpected. The text font in square and circle fixed annotations should be automatically adjusted to the specified size of the annotation style when the text is larger than than the style size. Auto sizing the text font is not applicable to rectangle style, which has been recently added to fixed styles. For rectangle style sizing is reversed, instead of the text font being auto sized, the rectangle is sized based on the text.  Of course, fixed styles size is modifiable in the Build Instruction Setup if you wish to use a font that results in a text size larger than the default annotation style.

![Screenshot - 06_10_2019 , 10_33_37](https://user-images.githubusercontent.com/13388970/66266402-ecc04100-e824-11e9-83d8-8faedc96acfb.png)

> So I right click on the offending annotations to change font size, it worked but... I had to do that for each and every submodel AND for round and square box style annotations...
I'll email you a link to the model / BI files

Here is what I am seeing with `0 !LPUB PLI SQUARE_STYLE FONT "Arial,18,-1,5,50,0,0,0,0,0,Normal"`

![Screenshot - 06_10_2019 , 10_26_41](https://user-images.githubusercontent.com/13388970/66266451-82f46700-e825-11e9-8a37-2f9b54dd9182.png)

And here with the default font and annotation style size.

![Screenshot - 06_10_2019 , 10_43_17](https://user-images.githubusercontent.com/13388970/66266572-298d3780-e827-11e9-92fc-5561a07b2dcd.png)

![Screenshot - 06_10_2019 , 10_46_28](https://user-images.githubusercontent.com/13388970/66266573-298d3780-e827-11e9-8739-9af4dbb4ab74.png)

Is the behaviour on your system different ?

Cheers,

**Comment by ZPhilo** [comment]
Yes, it's different, here is what I get:
Round annotation, default font
![defaultfontrnd](https://user-images.githubusercontent.com/5137285/66268223-95799b00-e83b-11e9-904b-55f851c9d6dd.JPG)
Round annotation, Arial 18
![font18rnd](https://user-images.githubusercontent.com/5137285/66268219-94e10480-e83b-11e9-88c2-450090bc0963.JPG)
Square annotation, default font
![defaultfontsq](https://user-images.githubusercontent.com/5137285/66268221-94e10480-e83b-11e9-92f4-d00a6827a205.JPG)
Square annotation, Arial 18
![font18sq](https://user-images.githubusercontent.com/5137285/66268222-95799b00-e83b-11e9-8599-89973899df71.JPG)

**Comment by trevorsandy** [comment]
Hi Philo,

I've added a change to the PLI annotation behaviour at r56 - see last 2 commits to #229. Previously, LPub3D i.e. at r46, would automatically attempt to resize annotation text font to fit the specified style "fixed size" only if the text width exceeded the the specified fixed size width. This limit would cause the text to be malformed when the text font height exceeded the fixed height height. The change at r56 resizes the text font if either the fixed size width or height is exceeded by the font size.

You can access the latest build at [Continuous Build 1568 (r57)](https://github.com/trevorsandy/lpub3d/releases/tag/continuous).

If the behaviour above persists in r56, do not hesitate to add an update to this ticket.

Cheers,
