### ISSUE TITLE
LDCad flexible parts don't get new parts per step highlighting

### ISSUE THREAD

**Issue by ZPhilo** [trevorsandy/lpub3d#354]
### Subject
LDCad flexible parts don't get new parts per step highlighting

### Environment
* Version of LPub3D - 2.3.13/1511
* Operating system - Win10/64
Motors with flexible cables, done using LDCad templates, are not highlighted when added to a step.
I'll email you a link to the model / BI files

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Indeed. I can reproduce this behaviour.

I'm looking at the BI file and noticed the _controlplusmotorl-lq-1.ldr_ does not generate any content; hence, no highlight model file is generated. 

Notice controlplusmotorl-lq-1.ldr and controlplusmotorl-lq-1-highlight.ldr are 0 KB
![Screenshot - 06_10_2019 , 11_53_54](https://user-images.githubusercontent.com/13388970/66267333-05822400-e830-11e9-8b11-fc5b3b2f50a4.png)

However the other motors with flexible cables are properly generated.

![Screenshot - 06_10_2019 , 11_59_46](https://user-images.githubusercontent.com/13388970/66267474-6100e180-e831-11e9-86a4-8b12a28ea367.png)

Notice in the image above, the fixed color subpart is not highlighted. This is because this part is not on the fixed color part list. When new parts are added to the library, it is a good idea to update the _fadeStepColorParts.lst_ by running Generate Static Color Parts List.

![Screenshot - 06_10_2019 , 13_31_13](https://user-images.githubusercontent.com/13388970/66268437-b17e3c00-e83d-11e9-9c82-51b352d3ec10.png)

Cheers,

**Comment by trevorsandy** [comment]
Implemented,

Cheers,
