### ISSUE TITLE
No difference of image when switching between orthografic and perspective view

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#378]
### Subject
Between switching ortografic and perspective mode by using LDView render, there is no different of the image on the page. Tried a lot of settings and also clear all caches.
The Modell is always presented from an ortographic point of view.

### Environment
2.3.13 all versions
W10 x86,x86_64

### Steps to reproduce
For the models that are very long, you can see the problem best.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

With v2.3.13 you can set the LDView renderer to use a non-ortho projection using the new “Additional renderer arguments” dialogue - See #332. The setting is `-FOV=<a>`, where a is a degree between `0.01` and `90`. 

Here is the FOV documentation from LDView help:

> Field of view (Default: 45)
> 
> Enter a number in this field to control the field of view (in degrees). Setting this to the minimum value of 0.1 will produce an image that is essentially orthographic. Setting it to the maximum value of 90 will produce a wide-angle view.


In LPub3D, when you set the renderer projection to Perspective and your Preferred Renderer as LDView, the default FOV (0.01) is replaced with the FOV value you specify - e.g from the CSI/PLI context menu; however, this value is assigned to the L3P Camera Angle setting `-ca<a>` which, I recently discovered, behaves differently from directly using the LDView `-FOV=<a>` setting described above.

cheers,

**Comment by trevorsandy** [comment]
The reason there is no difference between projections is because the model is rotated by LPub3D. You must also set the "Apply Camera Angles" flag to "Renderer" on the General tab of the Preferences dialogue. However, the result will likely be an empty page as the calculated camera distance which takes into account LDU, Resolution, Page Width and Image Scale is a number quite large - e.g. 3993775. While the distance value is valid when used with the L3P Camera Globe `-cg<lat>,<lon>,<radius>` and Camera Angle `-ca<a>` flags where the Camera Angle is to 0.01 which essentially is an orthographic view, this value is way, way, too large when the `-FOV=<a>` flag is used. Consequently, the image will be less than 1 pixel when the Camera Angle / FOV is set to as low as 0.001. 

This behaviour has been updated.

First: When selecting LDView as the preferred renderer along with Perspective Projection, the "Apply Camera Angles" flag will automatically be set to Renderer.

![Screenshot - 31_10_2019 , 12_43_20](https://user-images.githubusercontent.com/13388970/67944202-36aa0600-fbdc-11e9-83a4-a7700444c1b2.png)
![Screenshot - 31_10_2019 , 12_45_34](https://user-images.githubusercontent.com/13388970/67944316-783ab100-fbdc-11e9-845b-e6c275ee03f8.png)

Second: In order to manipulate the camera distance value and preserve the current LPub3D behaviour. I've created the LDView-specific distance factor flag `-LDViewPerspectiveDistanceFactor`. The value specified with this flag should be considerably less that a tenth of a percent of the calculated distance factor. This value is multiplied by the calculated camera distance to achieve a reasonable distance value that presents the rendered image roughly the size of its Orthographic counterpart.  The distance factor must be used with the FOV flag and Latitude/Longitude Camera Angles. As you can see in the example shown below this command syntax will require 2 lines:

&nbsp;&nbsp;&nbsp;- `0 !LPUB ASSEM LDVIEW_PARMS GLOBAL "-PerspectiveDistanceFactor=0.00006 -FOV=90"`
&nbsp;&nbsp;&nbsp;- `0 !LPUB ASSEM CAMERA_ANGLES LOCAL 30.0000  0.0000`

![Screenshot - 31_10_2019 , 12_37_36](https://user-images.githubusercontent.com/13388970/67943844-41b06680-fbdb-11e9-940a-e8f28505b286.png)

You can add these renderer arguments using the "Add LDView Renderer Arguments" context menu item.

![Screenshot - 31_10_2019 , 12_50_57](https://user-images.githubusercontent.com/13388970/67944681-47a74700-fbdd-11e9-9538-bfec196db585.png)

![Screenshot - 31_10_2019 , 12_48_53](https://user-images.githubusercontent.com/13388970/67944686-49710a80-fbdd-11e9-8fda-4f6982859dc3.png)

Cheers,

**Comment by technicbasics** [comment]
Hi Trevor
Works fine.
Small question: How can I reset to the default settings?
Once the syntax is set, it will be applied everywhere, even in the submodels.
This is disturbing for certain models.

**Comment by trevorsandy** [comment]
Hi Johann,

At the desired step, add the meta command you wish to reset without the GLOBAL or LOCAL scope setting. 

Also, if you are using the extra renderer parameters command e.g. `LDVIEW_PARMS`, and wish to apply the parameters in a limited scope, do not use the GLOBAL scope setting at the initial command. 

Cheers,
