### ISSUE TITLE
MODEL_SCALE ignored when using callouts

### ISSUE THREAD

**Issue by jensbruehl** [trevorsandy/lpub3d#385]
### Subject
When I use Callouts the MODEL_SCALE command to zoom the main model will be ignored. On pages without callout it works. I see this problem only when LDView Single Call is activated.

### Environment
* LPub3D - v2.3.13 r97
* Windows 10 x86_64

### Steps to reproduce
Load this mpd-file:

0 FILE main.ldr
0 Name: Main
0 !LPUB ASSEM MODEL_SCALE  0.5000
1 2 0 0 0 1 0 0 0 1 0 0 0 1 3865.dat
0 STEP
0 !LPUB CALLOUT PLI PER_STEP FALSE
0 !LPUB CALLOUT BEGIN
1 16 0 -24 0 1 0 0 0 1 0 0 0 1 subModel-1.ldr
0 !LPUB CALLOUT POINTER CENTER 0 0.498815 0.347032 0 0 0 0 0 0 1
0 !LPUB CALLOUT END
0 STEP
0 NOFILE 
0 FILE submodel-1.ldr
0 Name: submodel-1.ldr
0 Author: Undefined
1 4 0 0 0 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 4 0 -24 0 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 4 0 -48 0 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
1 4 0 -72 0 1 0 0 0 1 0 0 0 1 3001.dat
0 STEP
0 NOFILE 

Enable LDView Single Call:
![image](https://user-images.githubusercontent.com/50247249/70646300-e5634c80-1c46-11ea-8b64-e81fa412f674.png)

### Expected behaviour
Page 2 should look like this (!LPUB ASSEM MODEL_SCALE  0.5000):
![image](https://user-images.githubusercontent.com/50247249/70646406-1e032600-1c47-11ea-8919-5ac3d6503e9c.png)

### Actual behaviour
The model is shown with SCALE 1:
![image](https://user-images.githubusercontent.com/50247249/70646451-38d59a80-1c47-11ea-9baf-16938348e81e.png)

### Workaround
Disable LDView Single Call or use previous release LPub v2.3.13.0

**Comment by trevorsandy** [comment]
Hello Jens,

Thank you for reporting this behaviour. I've added an update that produces the expected layout. The update parses each PLI or CSI part in the 'SingleCall' stack and applies the render attributes specified for that part when it was processed. This means the layout will show the page as you have illustrated where the assembly is scaled to 0.5 as it is in the 'main' model and the submodel in the callout will scale to the default 1.0.

![Screenshot - 16_12_2019 , 10_45_07](https://user-images.githubusercontent.com/13388970/70896538-29f93a00-1ff1-11ea-82c7-548418eb7b52.png)

Cheers,

**Comment by trevorsandy** [comment]
Updates checked in for #387 corrects the unexpected behaviour introduced by the updates for this ticket. 

These new updates improve the LDView single step behaviour by allowing individual render parameters for each file in a single call stack. This means, for example, if you choose to specify different renderer parameters for each step on a multistep page (scale, camera angle, additional LDView flags etc...), parameters for each step's image will be passed to LDView because these parameters are now passed to and are managed in the single step render routine.

Cheers,
