### ISSUE TITLE
[Reopened] LPub3D inserting extra INSERT MODEL/INSERT PAGE

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#44]
Details as per issue #39, which has been marked as closed but still occurs with release 2.2.1.

The attached zip file contains two example LDR files. motor_pin.ldr exhibits the behaviour described in issue #39. motor_pin_01.ldr does not exhibit the behaviour described in issue #39. The difference between the two files is that motor_pin.ldr contains "0 STEP" as the last line in the file (line 9), while motor_pin_01.ldr does not contain "0 STEP" as its last line.

It appears that the logic detecting whether or not the model already contains the commands "0 !LPUB INSERT MODEL" and "0 !LPUB INSERT PAGE" is failing to take into account the (any?) trailing command.

[motor_pin_2.zip](https://github.com/trevorsandy/lpub3d/files/1869935/motor_pin_2.zip)

**Comment by trevorsandy** [comment]
Thanks for the additional details. 

The `0 !LPUB INSERT MODEL` meta command was designed to be automatically added as the last step [final model] if Fade Step is ON. By design, it can also be used manually anywhere in the model. The automatic placement logic starts at the end of the main model file and traverses backward until it encounters `0 !STEP`, `0 !ROTSTEP`, StepGroup, or `0 !LPUB INSERT MODEL`.

If you manually insert `0 !STEP` after an existing `0 !LPUB INSERT MODEL` meta command, LPub3D, by design, will ignore this occurrence of INSERT MODEL and insert a final model’s `0 !LPUB INSERT MODEL` meta command. It looks like this is the behaviour you are experiencing with motor_pin.ldr.

As I am writing this, I can think of a scenario where a `0 !LPUB INSERT MODEL` meta may be added unexpectedly which is after another ‘insert’ meta command - e.g. BOM, Picture etc... where a `0 !STEP` command separates the insert command(s). I will change the logic for this scenario to test for lines starting with 1 - 5 after encountering `0 !STEP`as the pre-condition to inserting the INSERT MODEL command versus only testing for `0 !STEP`. This change will not affect the scenario you presented which will continue as designed.

Cheers,

**Comment by trevorsandy** [comment]
I have corrected the behaviour I raised in my original message response and also changed the logic to overlook the ending STEPs that do not contain lines starting with 1-5 when determining the availability of the final model meta command. This logic change addresses the behaviour described in the original issue.
