### ISSUE TITLE
dll errors when starting LPub3D_x64.exe

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#45]
### Subject of the issue
After upgrading to LPUB3D version 2.2.1 I am unable to startx64 bit version of LPUB3D
C:\Program Files\LPub3D\LPub3D_x64.exe
It comes with two errors that says the following dll's are missing:
quazip.dll and ldrawini.dll
If i search the install folder the closest I can find is the following:
C:\Program Files\LPub3D\QuaZIP07.dll
C:\Program Files\LPub3D\LDrawIni161.dll

C:\Program Files\LPub3D\LPub3D22.exe starts with no problem.

### Your environment
* Version of LPub3D - see Help->About LPub3D: 
Version 2.2.1 Revision 0 Build 824 Hash g2f278ed
* Operating system - OS Name, Processor, Architecture (x86,x86_64) 
Windows 10 Pro, Intel Core I7 870 2.93GHz, X64 Bit version

### Configuration
[Note: Provide details and content below as needed with appropriate redactions]
* LPub3D installation path
  - Windows: C:\Program Files\LPub3D\
* Application data path 
  - Windows: %USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\
* Renderer configuration files
  - `[Application data path]/3rdParty\ldview-4.3\config\ldview.ini`
  - `[Application data path]/3rdParty\ldview-4.3\config\ldviewPOV.ini`
  - `[Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.conf`
  - `[Application data path]/3rdParty\lpub3d_trace_cui-3.8\config\povray.ini`
* Registry Extract
  - Windows: `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" LPub3D_Hive.reg`  

### Logging
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
As this has nothing to do with any renderer I have not added logs from them. And it does not seem that this error gets logged in the above log.

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other
Screenshots of the above attached.

### Steps to reproduce
Tell me how to reproduce this issue.  
Try starting C:\Program Files\LPub3D\LPub3D_x64.exe

### Expected behaviour
Tell me what should happen
LPub3D x64 version should start.

### Actual behaviour
Tell me what happens instead
See attached Error Sceenshots. after this no more happens

### Workaround
[LPUB3D.zip](https://github.com/trevorsandy/lpub3d/files/1878647/LPUB3D.zip)

Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Somehow your install folder now contains both new and old LPub3D distribution files. The new LPub3D22.exe is 64bit. Read on...

The files:

> C:\Program Files\LPub3D\QuaZIP07.dll
> C:\Program Files\LPub3D\LDrawIni161.dll
> C:\Program Files\LPub3D\LPub3D_x64.exe

are from LPub3D version 2.0.19.

Since v2.0.20, the LPub3D executable name is LPu3D<major version><minor version>.exe. If you installed the Windows Installer distribution, the installed instance of LPub3D will match the OS architecture so x86_64 (64bit) will be automatically installed if your  OS is Windows 64bit and vice versa. You can quickly determine the architecture installed by right-clicking the LPub3D executable and selecting properties, and raising the 'details' tab. Your should see something like this (this example is Windows 10)

![screenshot - 05_04_2018 07_55_15](https://user-images.githubusercontent.com/13388970/38350339-252830f0-38ab-11e8-9a3f-9ae8c30d28ca.png)

Or navigating to Settings/Apps & Features and typing 'LPub3D' in the search dialogue. On Windows 10, you will see something like this:

![screenshot - 05_04_2018 08_29_50](https://user-images.githubusercontent.com/13388970/38350477-ba7a32e8-38ab-11e8-8ea7-3e3d78c7ec82.png)

If you ran the Windows Installer distribution of LPub3D (e.g. [LPub3D-2.2.1.0.824_20180331.exe](https://github.com/trevorsandy/lpub3d/releases/download/v2.2.1/LPub3D-2.2.1.0.824_20180331.exe)), the old version should be automatically uninstalled - if the old version was also installed with the Windows Installer.

If your are updating an instance of LPub3D that was previously installed from LDraw.org All-In-One-Installer (AIOI), then I imagine the previous version of LPub3D was not uninstalled or not uninstalled completely. I am not familiar with the details of the AIOI installation steps, you will have to follow up with the guys at LDraw.org about that.

If you were running a portable distribution of LPub3D (e.g. [LPub3D_x86_64-2.2.1.0.824_20180331.zip](https://github.com/trevorsandy/lpub3d/releases/download/v2.2.1/LPub3D_x86_64-2.2.1.0.824_20180331.zip)), then you are well advised to not install the new version of LPub3D in the same location.

The distribution files for v2.0.19 are independent of those for v2.2.1 and, in fact, if all distribution files are present both instances will run from the same install location. However, be advised that some registry keys will be shared between both applications and this scenario has not be extensively tested. 

So as you can no longer run your old version of LPub3D, I imagine some of the files for that instance are no longer present. I believe your best approach going forward is to uninstall both applications and reinstall each (if that is what you want) in their own location.

Let me know if you are able to progress with this information.

Cheers,

**Comment by snakebyte73** [comment]
Hi Trevor
Thanks for the help.
I uninstalled it again and as you can see below it left a lot of files.
![billede](https://user-images.githubusercontent.com/38093610/38351297-205badaa-38af-11e8-8f25-8970c20e3546.png)

I then manually deleted all the lefter over files and reinstalled the version described earlier.
When I start C:\Program Files\LPub3D\LPub3D22.exe i works fine.


/Knud

**Comment by trevorsandy** [comment]
Hi Knud - I’m pleased to see you are progressing.

The version 2.2.1 uninstall program does not know those files are there, this is why they are left behind.

On my side I’ll take a look at the old v2.0.19 install/uninstall scripts to see if the left over files are somehow excluded from the uninstall program. If they are, i’ll update the v2.2.2 uninstall program to manually cleanup the left over files.

Cheers,
