### ISSUE TITLE
Do not save fade steps and/or highlight step final model step

### ISSUE THREAD

**Issue by trevorsandy** [trevorsandy/lpub3d#483]
Do not save fade steps and/or highlight step final model step and automatically generate the final step when the model is loaded.
### Environment
Version of LPub3D - 2.4.1
Operating system - All

### Solution
Do not save fade steps and/or highlight step final model step and add global setup flag to enable or disable the final model step automatic generation when fade steps / highlight step is enabled. 

![Screenshot - 21_11_2020 , 16_02_50](https://user-images.githubusercontent.com/13388970/99880347-1f88ec80-2c13-11eb-90e0-f4ef45d9b829.png)

Cheers,

**Comment by trevorsandy** [comment]
Implemented.

Cheers,

**Comment by jacovandermolen** [comment]
Would it be possible to activate the Highlight step in certain steps? So the default is off, but specify locally for an assembly or step to generate highlight?

**Comment by trevorsandy** [comment]
This behaviour is not formally implemented. However, I imagine you can achieve this display using the high contrast stud style setting and changing the edge colour to your desired setting. 

Note that stud styles and automate edge colours can be enabled at the project, CSI, PLI and SMP (model preview at first sub-model step) levels. You can generate the appropriate meta commands from the respective setup dialogues.

Cheers,

**Comment by jacovandermolen** [comment]
OK, I see. And stud-styles can be applied locally?

**Comment by trevorsandy** [comment]
Yes, it is designed to be applied LOCAL but I haven’t tested this use case.

Cheers,

**Comment by jacovandermolen** [comment]
Interesting. I have tried, but no succes.
In the DevOps version I am using now (2.4.0.326), highlight renders all new parts in a step black (dark)
Exporting to PDF of PNG crashes. This seems due to the last 2 lines:

0 // The following 3 command lines were auto-generated for fade or highlight step.
0 // Use 0 !LPUB INSERT DISPLAY_MODEL to override automatic insertion and deletion.
0 STEP
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE

Saving the file and opening it is a text editor does not show these 

Without highlight on, a PDF or PNG is made.

![afbeelding](https://user-images.githubusercontent.com/32261647/107483066-cfba2180-6b80-11eb-8d6f-38670776d67c.png)

[edgetest.mpd.txt](https://github.com/trevorsandy/lpub3d/files/5956744/edgetest.mpd.txt)

**Comment by trevorsandy** [comment]
Hi Jaco - thanks for reporting this edge behaviour. I'll take a look.

Could you move this update to it's own ticket so I don't misplace it ? 

Cheers,

**Comment by jacovandermolen** [comment]
Sure:
https://github.com/trevorsandy/lpub3d/issues/502

**Comment by trevorsandy** [comment]
Implemented.

Cheers,
