### ISSUE TITLE
continuous submodel rewrite makes editing slow and cumbersome

### ISSUE THREAD

**Issue by DanieleBenedettelli** [trevorsandy/lpub3d#485]
*QUESTION*
Each time I create a callout pointer, I move a CSI inside a page, or I switch page, LPUB3D updates the submodels in the tmp folder, making editing super slow. 
I don't remember this happening some time ago. Is it needed to refresh all the submodels in the tmp folder even if I add meta commands that do not modify the actual content of the submodels?

**Comment by trevorsandy** [comment]
> LPUB3D updates the submodels in the tmp folder, making editing super slow. Is it needed to refresh all the submodels in the tmp folder even if I add meta commands that do not modify the actual content of the submodels?

This behaviour should only occur when the model file is loaded and if all the submodels have been modified. You can see in the log which submodels have been written to the tmp folder on a page  reload/update. On 'redraw' all submodels are written because the model file is reloaded.

What version of LPub3D are you using ? Version 2.4.0 introduced new behaviour that indeed did considerably slow page processing. The new behaviour performance is improved in 2.4.1 which is soon to be released.

Cheers,

**Comment by DanieleBenedettelli** [comment]
Hi Trevor.
I was using 2.3.13, now updated to 2.4.0 hoping to work faster. After what
you said I'm early waiting for the next release.

Thanks
D

Il mar 24 nov 2020, 10:36 Trevor SANDY <notifications@github.com> ha
scritto:

**Comment by trevorsandy** [comment]
Excellent - 

You can check the [lpub3d-ci repo releases](https://github.com/trevorsandy/lpub3d-ci/releases) for the latest development builds if you care to have an advance look. If you do, let me know if your performance improves.

Cheers,

**Comment by DanieleBenedettelli** [comment]
Performance is much better with 2.4.0.


D

Il giorno mar 24 nov 2020 alle ore 13:21 Trevor SANDY <
notifications@github.com> ha scritto:
