### ISSUE TITLE
LPub3D crashes switching Preferences to Enable Fade Steps

### ISSUE THREAD

**Issue by d-j-m-0** [trevorsandy/lpub3d#49]
### Subject of the issue
When switching LPub3D from not generating fade steps to generating fade steps via the Preferences dialog window, LPub3D crashes.

### Your environment
* Version of LPub3D - 2.2.1 Revision 0 Build 824
* Operating system - Windows 10, 64 bit, Intel i7-7660U, x64

### Configuration
* LPub3D installation path
  - Windows: `D:\Program Files\LPub3D`
* Application data path 
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry Extract
  - Windows: contained within attached zip file

### Logging
* Application Log: contained within attached zip file

### Screenshots
![preferences_crash](https://user-images.githubusercontent.com/37604323/38460438-d6846c4c-3b0d-11e8-8ccb-93d6b622b672.png)

### Steps to reproduce
1) Run LPub3D.
2) Open Preferences dialog. Untick the "Enable Fade Steps" if it is ticked. Close the dialog.
3) Exit LPub3D
4) Run LPub3D
5) Open Preferences dialog. Tick the "Enable Fade Steps". Close the dialog.
6) LPub3D crashes.

### Expected behaviour
LPub3D should not crash.

### Actual behaviour
LPub3D crashes, creates a dump file and displays a dialog window (as per screenshot).

### Workaround
After LPub3D crashes, once run again it has remembered the switch to generating fade steps.

### Solution suggestion
No idea.

[sbrick_example.zip](https://github.com/trevorsandy/lpub3d/files/1886741/sbrick_example.zip)

**Comment by trevorsandy** [comment]
Thanks for the write-up. 

I know this issue. I haven’yet Figured out how to correct it. Its caused by some new code (since LPub3D 2.0.20) in the 3DVirwer’s (LeoCAD) LDraw Library load program (the Mutex function is not happy to reload the library;-) The segfault is thrown at line 7 on the stack trace below.

NEW - LPUB3D-LIBRARY-RELOAD [SEGFAULT]
1	std::__atomic_base<QMutexData*>::compare_exchange_strong	atomic_base.h	752	0xb008cdb
2	std::atomic<QMutexData*>::compare_exchange_strong	atomic	462	0xb008cdb
3	QAtomicOps<QMutexData*>::testAndSetAcquire<QMutexData*>	qatomic_cxx11.h	290	0xb008cdb
4	QBasicAtomicPointer<QMutexData>::testAndSetAcquire	qbasicatomic.h	262	0xb008cdb
5	QBasicMutex::fastTryLock	qmutex.h	101	0xb008cdb
6	QMutex::lock	qmutex.cpp	224	0xb008cdb
7	QMutexLocker::QMutexLocker	qmutex.h	200	0x688dfe
8	lcZipFile::ExtractFile	lc_zipfile.cpp	595	0x48a310
9	lcPiecesLibrary::ReadArchiveDescriptions	lc_library.cpp	543	0x4437c4
10	lcPiecesLibrary::ReloadUnoffLib	lc_library.cpp	3457	0x44ffe5
11	PartWorker::processPartsArchive	threadworkers.cpp	966	0x62c6b1
12	PartWorker::processFadeColourParts	threadworkers.cpp	498	0x6271b7
13	PartWorker::qt_static_metacall	moc_threadworkers.cpp	142	0x65d24f
14	QMetaObject::activate	qobject.cpp	3766	0xb18d52b
15	QMetaObject::activate	qobject.cpp	3628	0xb18d7bf
16	QThread::started	moc_qthread.cpp	158	0xb00b1e7
17	QThreadPrivate::start(void*)*4	qthread_win.cpp	376	0xb00fbb9
18	KERNEL32!BaseThreadInitThunk	0x73de8654		
19	ntdll!RtlGetAppContainerNamedObjectPath	0x77014a77		
20	ntdll!RtlGetAppContainerNamedObjectPath	0x77014a47

**Comment by trevorsandy** [comment]
Corrected. Many thanks to Leonardo Zide for going out of his way to provide this fix.
