### ISSUE TITLE
Export to PDF crash and highlight current step renders bricks completely dark

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#502]
In the DevOps version I am using now (2.4.0.326), there are two unexpected behaviours:

1. Highlight renders all new parts in a step black (dark)

2. Exporting to PDF of PNG crashes.
This seems due to the last 2 lines:

```
0 // The following 3 command lines were auto-generated for fade or highlight step.
0 // Use 0 !LPUB INSERT DISPLAY_MODEL to override automatic insertion and deletion.
0 STEP
0 !LPUB INSERT MODEL
0 !LPUB INSERT PAGE
```

Saving the file and opening it is a text editor does not show these 

Without highlight on, a PDF or PNG is made.

![afbeelding](https://user-images.githubusercontent.com/32261647/107483066-cfba2180-6b80-11eb-8d6f-38670776d67c.png)

[edgetest.mpd.txt](https://github.com/trevorsandy/lpub3d/files/5956744/edgetest.mpd.txt)

_Originally posted by @jacovandermolen in https://github.com/trevorsandy/lpub3d/issues/483#issuecomment-776536555_

**Comment by trevorsandy** [comment]
Corrected. 

> 1. Highlight renders all new parts in a step black (dark)

The cause of this behaviour is a malformed !COLOUR meta command as a result of a recent update to the LPub3D color class. This behaviour has been corrected.

> Exporting to PDF of PNG crashes.

This behaviur is caused by the currentDisplayPage index variable not being set before assignment so that the index reflected the actual display page number; thus, causing an index overflow abnormal end. This behaviour has been corrected.

![Screenshot - 10_02_2021 , 16_52_35](https://user-images.githubusercontent.com/13388970/107534733-6a862080-6bc0-11eb-9d47-a8a7d7fc9bad.png)

Cheers,

**Comment by jacovandermolen** [comment]
Great!
Now what I am looking for is to only highlight the submodel in step 4. Thus setting highlight locally only in that step. So not the steps in the callout, but only the submodel now yellow outlined in step 4.
Referenced here: https://github.com/trevorsandy/lpub3d/issues/483#issuecomment-775849688

This example is part of a larger model that has some landscape and hills, all in green. Now it is hard to make out where the submodels of the hills supposed to go.

**Comment by trevorsandy** [comment]
Take a look at #505. 

It's still a work in progress so do not hesitate to let me know if you encounter any unexpected behaviour.

Cheers,

**Comment by trevorsandy** [comment]
Fixed.

Cheers,
