### ISSUE TITLE
Parts not showing correctly in LPub3D

### ISSUE THREAD

**Issue by snakebyte73** [trevorsandy/lpub3d#568]
### Subject
Hi

I am having a little trouble with some specific parts.
for example: 3069bpsa.dat
It is not shown correctly in LPub3D.

It seems i have the same issue with 63965a.dat
If i change to 63965.dat instead it is shown correctly in LPub3D
But 63965.dat is a depricated part.

And the same issue with 98138pm9.dat

In LDCad all three parts are shown correctly.

I have tried downloading and installing the newest complete.zip and ldrawunf.zip
All other files seems to be shown correctly

LPub3D:
![Pic01](https://user-images.githubusercontent.com/38093610/129481295-300c681a-8aec-4058-8ffa-8bb4cf9c9240.png)

LDCad:
![Pic02](https://user-images.githubusercontent.com/38093610/129481298-a12213c0-09fb-482a-a2c8-280238aa8889.png)

Parts in LDCad:
![Pic03](https://user-images.githubusercontent.com/38093610/129481299-d8ef176f-b15f-4503-893d-4dc65a66e7ca.png)

### Environment
* Version of LPub3D - Release 2.4.3 Rev 0 Build 2557
* Operating system - Windows 10 x64

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\Program Files\LPub3D` [x86_64]
* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`
  - Windows (portable): `<application path>\config\LPub3D Software\LPub3D.ini`
  - macOS: ` ~/Library/Preferences/com.lpub3d-software.LPub3D.plist`
  - Linux: `~/.config/LPub3D Software/LPub3D.conf`
  - AppImage (Linux): `~/.config/LPub3D Software/<AppImage File Name>.conf`
* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce
Tell me how to reproduce this issue.
Provide a sample mpd/ldr file that reproduces the problem.

### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Workaround
Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by snakebyte73** [comment]
Hi again
I have done a little more testing and it seems that the problem is the native renderer.

**Comment by technicbasics** [comment]
Hi
Works here fine.
Did you update the library files in LPub?

**Comment by snakebyte73** [comment]
When i try to update both via LPub it comes with a connection error.
![billede](https://user-images.githubusercontent.com/38093610/130596914-3a5ceb1d-6d38-4cf9-8a09-0ce2383b2a58.png)

**Comment by technicbasics** [comment]
Hi
I suspect that you are using the portable version.
Do a manual update of the library.
Copy both the complete.zip and the ldrawunf.zip from your Ldraw directory to the directory where LPub3D is located.
There is a folder called "libraries".
This is where the files have to go.
Then you have to rename the file ldrawunf.zip to lpub3dldrawunf.zip.
Regards Johann

**Comment by snakebyte73** [comment]
Hi Johann
Thanks for the input.
It is not a portable edition i am running, it has been installed with the installer.
It helped updating the zip files .

Thanks
Knud

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

The Windows only _Error connecting to update server. Error creating SSL context()_ message is triggered when there was an error establishing a connection to the server hosting the credentials that enables LPub3D to download updated libraries. This error is most likely caused by an outdated or missing SSL library so I've written a routine that logs the status of the SSL library installed with LPub3D (_files libcrypto-1_1.dll_ and _libssl-1_1.dll_). If you are experiencing the above message, It could be helpful to check the LPub3D logs for the following load message.

Valid SSL library installed:
`INFO int Application::initialize(void) @ln 1002 "Secure Socket Layer..........(Supported, Build: OpenSSL 1.1.1g  21 Apr 2020, Detected: OpenSSL 1.1.1m  14 Dec 2021)" `

Invalid SSL library installed:

The library should match the compiled version of LPub3D - actually, it should match the version of the Qt platform build currently at 5.15.2. Release builds for Windows will include a valid library but from time-to-time, users are reporting the behaviour described above. It is difficult for me to find the root cause because on my dev and personal machines, I have never received this message. all downloads work as expected.

Cheers,

**Comment by nathaneltitane** [comment]
@trevorsandy experiencing this on native renderer with 2.44 OBS Ubuntu 22.04 build still.
LPub should work with a version agnostic library and just function around a generic ldraw path that is common to all ldraw editors on the system.

this would prevent redundancies and issues revolving around custom parts and the maintenance of several directories with duplicate ldraw archives/dirs.

@app4soft

**Comment by trevorsandy** [comment]
If you continue to experience this behaviour on the latest release of LPub3D, do not hesitate to reopen this ticket.

Cheers,
