### ISSUE TITLE
TENTE parts outdated

### ISSUE THREAD

**Issue by jasoloz** [trevorsandy/lpub3d#583]
### Subject
TENTE parts added in #132 are outdated. You can find the link to the updated zip file in the first post of this topic: 
https://www.tenteros.land/foro/viewtopic.php?p=1121#p1121
It is a Dropbox link, but Dropbox changes the URL each time I update the content (in the future I will put the parts on Github or similar). Meanwhile it is better to use the link of that post.

### Environment
* Version of LPub3D - Last version
* Operating system - All

### Solution suggestion
LPub3D should update the parts asking the user the folder used by LDraw editors such as LDCad, MLCad, etc. I think the program has that option, but it has never worked for me, I had to go to the LPub3D folder in AppData to update the parts (in Windows). Another solution would be to put those parts in a public repository with a fixed URL so LPub3D could check for updates and download the newest version.

**Comment by trevorsandy** [comment]
Hello Jasoloz,

Many thanks for the link. I did spend some time trying to find a reliable source for this library but did not succeed.

> Another solution would be to put those parts in a public repository with a fixed URL so LPub3D could check for updates and download the newest version.

Indeed, currently the TENTE parts library is stored on GitHub in my [lpub3d_libs repo](https://github.com/trevorsandy/lpub3d_libs/releases) as tenteparts.zip. At application build, this library is downloaded. 
I don't think I have added the behaviour to update the TENTE library from the LPub3D user interface as is the case for the LDraw LEGO official and unofficial libraries, because I did not believe this library was regularly updated.

Anyway, I've updated the tenteparts.zip library in the lpub3d_libs repo with the latest archive you provided. 

Lastly, if you don't mind, can you provide your name (and contact information) so I can properly add you to the [CREDITS.txt](https://trevorsandy.github.io/lpub3d/assets/docs/lpub3d/CREDITS.txt) file ? At the moment, I just have your ID as 'jasolo'. You can use my email if you do not wish to publicly display your information here.

Cheers,

**Comment by jasoloz** [comment]
The information will be public in the CREDITS.txt file, so no problem displaying it here.
Name: José Alfonso Solera
Email: jasolo.f@gmail.com

**Comment by trevorsandy** [comment]
Many thanks. I've updated the CREDITS file and [LPub3D site](https://trevorsandy.github.io/lpub3d/) reference.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

Cheers,
