### ISSUE TITLE
Dormant popup screens

### ISSUE THREAD

**Issue by aefferenpriv** [trevorsandy/lpub3d#590]
### Subject
There seem to be dormant popup screens while using LPub3D. I can't find out how to create them but when you hover over the menubar at the bottom of your screen these become available.

### Environment
* Version of LPub3D - 2.4.4 revision 0 build 2671 SHA oba24afe3
* Operating system - Windows 10, 64

### Configuration
* LPub3D installation path
  - Windows: `C:\Program Files (x86)\LDraw\LPub3D`

* Application data path
  - Windows: `%USERPROFILE%\AppData\Local\LPUb3D Software\LPub3D\`
  
* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg` - not found

* Renderer configuration files
  - `[Application data path]/ldv/ldvExport.ini`
  - `[Application data path]/3rdParty/ldglite-1.3/config/ldglite.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldview.ini`
  - `[Application data path]/3rdParty/ldview-4.4/config/ldviewPOV.ini`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.conf`
  - `[Application data path]/3rdParty/lpub3d_trace_cui-3.8/config/povray.ini`

### Steps to reproduce
1. open LPub3D
2. open a 'project'
3. on first page change the scale via the on screen right mouse click menu.
4. confirm changed scale
5. now hover over the LPub3D icon in menu bar,
6. hover over the thumbnail
7. now the menu screens appear again.

### Expected behaviour
I don't expect  to have the screens persistent in the background. While using regularly a lot are sticking and it seems creating irregular behavior like code lines duplicating when changing values.

### Actual behaviour
When confirming an action the screen should be fully gone.

### Workaround
Closing and restarting LPub3D regularly

### Solution suggestion
No solution availbel from my end
![image](https://user-images.githubusercontent.com/93044629/173153167-87bbd4d0-ed9b-4a74-9363-2062099c9b24.png)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

The dormant dialogs result from Windows not refreshing it's application window cache for the currently running application. In such a scenario, you may see previously opened windows when you hover over the application icon in the Windows tray. You will also notice that it is not possible to activate these dormant dialogs because they are not actual present.

I am not aware of anything I can do to clear these dialog windows as this functionality is exclusively controlled by Windows.

Cheers,
