### ISSUE TITLE
Defining scale in terms of LEGO units

### ISSUE THREAD

**Issue by laurensvalk** [trevorsandy/lpub3d#610]
When changing renderer, page size, or camera settings, I often end up re-adjusting most of the instructions because everything is a bit different.

So here is an idea for consideration: How about allowing scale and/or camera distance to be defined in terms of "LEGO Units per inch/cm of the page"?

Particularly for orthographic projections, this might make it easier to get consistent sizes of all assemblies and PLIs on the page, even when changing the DPI of the rendered output.

Or perhaps this is already possible? If so, what would be the right way to do it?

**Comment by trevorsandy** [comment]
Thank you for your suggestion.

> How about allowing scale and/or camera distance to be defined in terms of "LEGO Units per inch/cm of the page"?

The use of LDUs has always been used calculate the camera distance passed to the preferred renderers (LDView, LDGLite, Native).

The behaviour you are seeing is a result of the difference in the 'default units' used to position the camera in each of the renderers.

I could automate the behaviour to capture the 'from' renderer when switching renderer in order to calculate the
camera position adjustment between renderers but this update would not treat the use case of a user loading a model file rendered with a different renderer than the currently selected preferred renderer. As a result, I've implemented the ability to manually adjust the camera position between LDView, LDGLite and the Native renderer/3D Viewer.

You can manually adjust the default camera position by manipulating the Default Distance Factor value up or down to so that rendered images are reasonably the same size between renderers.

![Screenshot - 26_11_2022 , 06_34_16](https://user-images.githubusercontent.com/13388970/204073941-202258d0-c573-4c80-a4d0-a7103318180d.png)

Use the help (?) icon at the top right of the form the see further details on these and the other default camera settings.

Cheers,

**Comment by laurensvalk** [comment]
Thank you!
