### ISSUE TITLE
Request: OpenDocument Draw format support/help

### ISSUE THREAD

**Issue by billward** [trevorsandy/lpub3d#640]
I would like to fine tune the placement of model and part images, numbers, etc. when generating instructions.
In the past my workflow was:
1. Generate PDF from LPub
2. Run OpenOffice Draw with a PDF Import plugin installed
3. Open the PDF file - it generates an ODG file with all the LPub objects
4. Adjust as desired and save

I tried this using the latest versions of the relevant tools, as follows:

1. Generate PDF from LPub3D latest version
2. Run LibreOffice Draw and open the PDF
Instead of LPub objects, it seems there is just one giant bitmap file, and the bitmap isn't displaying properly. If I right-click on the big rectangle that represents the instructions, and select "Edit with External Tool" an image editor opens showing the LPub instructions as a large image.

Was there a change made to the way PDF files are generated? Looks like it is generating a PDF with a single large image instead of individual objects. The previous algorithm did have some alignment problems with the text that I always had to adjust but since I was doing that anyway, it was no problem.

In general the placement of objects in LPub3D is pretty good, but not quite ideal and is difficult to manipulate using the software. I'd rather use a tool optimized for that kind of editing instead.

Ideally it would be nice for LPub3D to offer an "export to ODG" format that would generate a file in the format that OpenOffice / LibreOffice would be able to edit. Is there any chance of this?

Alternately, "export to PowerPoint" would be nearly as useful for me, and more useful to most people.

Thanks.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

> 2. Run LibreOffice Draw and open the PDF
Instead of LPub objects, it seems there is just one giant bitmap file, and the bitmap isn't displaying properly. If I right-click on the big rectangle that represents the instructions, and select "Edit with External Tool" an image editor opens showing the LPub instructions as a large image.

> Was there a change made to the way PDF files are generated?

Yes and No. 

Yes, there was an in inadvertent change in v2.4.5 when resulted in unexpected export to PDF behaviour - see #624. This behaviour has been corrected.

No. The export to PDF behaviour is as follows:

1. Component images (Default option):
![Screenshot - 06_12_2022 , 06_13_59](https://user-images.githubusercontent.com/13388970/205823232-263a9ea4-ed40-4460-b61a-da3e36b3afb0.png)

2. Rendered page - you can select the assembly image when viewing the PDF file
![Screenshot - 06_12_2022 , 06_13_14](https://user-images.githubusercontent.com/13388970/205823282-aee2847a-13bc-4d5e-a058-76774bafab97.png)


3. Single Image Per Page: 
![Screenshot - 06_12_2022 , 06_13_52](https://user-images.githubusercontent.com/13388970/205823389-63cd25f9-ad9f-4ac5-996c-5fa165ba61e1.png)

4. Rendered page - you can only select the entire document page when viewing the PDF file
![Screenshot - 06_12_2022 , 06_15_12](https://user-images.githubusercontent.com/13388970/205823411-402df6f8-e378-41bd-bf63-985fddba05e7.png)

>Ideally it would be nice for LPub3D to offer an "export to ODG" format that would generate a file in the format that OpenOffice / LibreOffice would be able to edit. Is there any chance of this?

Indeed, this is on my _TODO_ list but I must say it is very low. The described behaviour along with _MS print to XPS document writer_ is in place to accommodate in the mean time.
 
![Screenshot - 06_12_2022 , 06_33_13](https://user-images.githubusercontent.com/13388970/205825575-7558cf59-8a2d-4fe5-87d2-87721de9adfb.png)

>Alternately, "export to PowerPoint" would be nearly as useful for me, and more useful to most people.

This alternative is not in play. I am not aware of an open source format that would support this.

If you are using v2.4.5 and not experiencing the above behaviour, it may be a result of #624. 

Having said all that, I expect to release v2.4.6 which includes the #624 correction shortly - within days.

Cheers,

**Comment by billward** [comment]
As a workaround I'm doing export to PNG and then importing that into my odg
file and doing a little cropping. I'd really rather be able to do more to
it to control the positioning of objects on the page but this will do for
now. I'm looking forward to the new release when it comes out and I will
try that

Sent from my phone (sorry if my reply is brief, ask me again when I'm at a
real keyboard)
