### ISSUE TITLE
Open with system editor

### ISSUE THREAD

**Issue by ErfinderDesRades** [trevorsandy/lpub3d#673]
LPub3D does not use the system editor (notepad++) although it is activated in the "Open with" menu. Instead of it it always uses the internal editor. 

Environment
Version of LPub3D - 2.4.6.0.3111_20230111
Windows 11, Processor 12th Gen Intel(R) Core(TM) i7-12700H 2.70 GHz
Architecture 64-Bit, 32 GB Ram
Configuration
LPub3D installation path
Windows: C:\Program Files\LPub3D_246
Application data path
Until now I couldn't find any workaround

Best regards and thanks a lot in advance.

**Comment by trevorsandy** [comment]
Thank your for reporting this behaviour. 

I will take a look.

Can you precise the steps to reproduce as there are multiple use cases where the system editor is available. 

For example, are you experiencing this behaviour when you use attempt to open the model file vial the 'Open With...' menu action, or are you attempting to open a parameter file using the system editor or are you attempting the open the current step model vial the context menu ?

Cheers,

**Comment by ErfinderDesRades** [comment]
Thank for your quick response.

This behaviour appears every time I try to edit textfiles.

When I try to edit parameter files it opens the file in the internal editor. In this editor there is a button "Open with System Editor"

<img width="51" alt="image" src="https://user-images.githubusercontent.com/77791504/214331991-b9e768a3-4683-43c5-b1c7-177fc4d8e237.png">

When I use this one the file will be opened in notepad++.

Or is this the intended way? Maybe my expectation was wrong.

When I try to edit the code file, it will also be opended in the internal editor. In that editor there is no "Open with" button. When I use the "Open with" button from the context menu

<img width="300" alt="image" src="https://user-images.githubusercontent.com/77791504/214333016-a6f4474c-cbdb-4340-8ca0-55874064c9c4.png">

the file will be opened in notepad++, but it will only show the parts without any LPub3D formatting

<img width="225" alt="image" src="https://user-images.githubusercontent.com/77791504/214333502-64607160-0e07-44eb-83fc-f0be09264c15.png">

Hope this will clarify the issue.

BR from Bremen

**Comment by trevorsandy** [comment]
Thank you for the details.

> When I try to edit parameter files it opens the file in the internal editor. In this editor there is a button "Open with System Editor"

To open a parameter using the designated system editor (the editor shown in the following shot)...

![Screenshot - 25_01_2023 , 13_53_13](https://user-images.githubusercontent.com/13388970/214568458-36a70cb0-ecc1-4b33-aa6b-ce4304f4f255.png)

You must check the menu flag 'Use System Editor'

![Screenshot - 25_01_2023 , 13_51_00](https://user-images.githubusercontent.com/13388970/214568605-d22591e1-505f-43b7-915b-df7e191d6fca.png)

When 'Use System Editor' is not checked, this paremeter file editor 'Open With...' menu action will open a loaded file using the 'system assigned' program for the file extension. This means that the file will not necessarily be opened in a text editor.

I have changed this behaviour to use the designated system editor (when defined) for files with .mpd,.ldr,.dat, and .lst extension

When editing the current model file, I am currently loading the viewer content (versus the actual model file with meta commands) when the 'Open With...' action is selected in the detached default editor. 

![Screenshot - 25_01_2023 , 15_47_40](https://user-images.githubusercontent.com/13388970/214594698-4b5e6aa4-1f50-4cf8-9c12-027c0c8d4e88.png)

I have changed detached editor 'Open With...' menu action to open the the actual model file with meta commands.

If you wish to edit the current model file in the system editor, use this menu action:

![Screenshot - 25_01_2023 , 13_53_13](https://user-images.githubusercontent.com/13388970/214568458-36a70cb0-ecc1-4b33-aa6b-ce4304f4f255.png)

or this one:

![Screenshot - 25_01_2023 , 15_47_40](https://user-images.githubusercontent.com/13388970/214594698-4b5e6aa4-1f50-4cf8-9c12-027c0c8d4e88.png)

The 'Open With...' context menu action:

![Screenshot - 25_01_2023 , 15_57_24](https://user-images.githubusercontent.com/13388970/214597197-d5c29e3c-94d8-4011-a497-3279dc48e6c3.png)

...is not intended to 'edit' the currently loaded submodel, rather it is intended to allow the editor view the currently loaded viewer content (content used to generate the current assembly image) which can be used to debug or otherwise troubleshoot errors and such.

Use the 'Edit ...' context menu action just above instead.

Cheers,

**Comment by trevorsandy** [comment]
The stated changes have been implemented.

Cheers,

**Comment by ErfinderDesRades** [comment]
Thanks a lot for your efforts.

Great app. Working really fine.

BR from Bremen

**Comment by trevorsandy** [comment]
With pleasure.

Cheers,
