### ISSUE TITLE
Stud Cylinder Color

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#702]
### Subject
Request:
I love the option "Stud Style", because there can also be changed the edge color of parts.
This is very nice for black parts, to increase visibility.
But it also has a small disadvantage:
In the same setting, you can also adjust the Cylinder colors of the studs.
It would be nice to be able to select these options individually as well. (Maybe with checkbox).
![2023-04-14 17_22_33-LPub3D Preferences](https://user-images.githubusercontent.com/49073781/232086910-d2955f31-3f0e-4d04-96a2-94afc33e21d4.png)

Reason: I am currently working on a model that consists almost entirely of Technic parts and has many black parts. Therefore I want to change the Edge color, but not the Cylinder colors.
You are probably wondering why?
Well, I also put 1/2 pins in light gray, by coloring the cylinders they now look like they are black.

Setting: 0 - Plain
![2023-04-14 17_08_55-Pistenbully 600 Polar V1 mpd - LPub3D v2 4 6 r144 (Release)](https://user-images.githubusercontent.com/49073781/232087090-60e529e8-4d04-4469-9853-3057c182198e.png)

Setting: 6 - High contrast and matched black edge color
![2023-04-14 17_10_10-Pistenbully 600 Polar V1 mpd - LPub3D v2 4 6 r144 (Release)](https://user-images.githubusercontent.com/49073781/232087116-5b4b6edb-c0b8-40a7-a496-ff7fca25bd94.png)

Solution: Either you could select the options individually as described above, or it would be possible to specify the colors not directly but in LDraw colors, e.g. to assign the color 16 to the cylinders so that they are not colored.

![2023-04-14 17_23_08-LPub3D Preferences](https://user-images.githubusercontent.com/49073781/232087180-a4414bed-ed78-4e56-80bf-af6756203868.png)

By the way:
2.4.6r144 runs very stable until now!

**Comment by trevorsandy** [comment]
Thank you for your request. It is an excellent enhancement.

I’ll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Note that while adding an enable flag for each colour option will add flexibility, it will not address the use case where both stud and 1/2 pin are present. In this case the stud cylinder colour behaviour will be on or off. This is so because when a high contrast stud style is selected, the default stud primitives (`stud...dat`) are replaced with an instance where the cylinder primitive (`4-4cyli.dat`) colour is hard coded to 4242 - e.g. `1 4242 0 -4 0 4 0 0 0 4 0 0 0 4 4-4cyli.dat`.

###  Workaround
To override the stud behaviour when high-contrast stud style is selected, add a custom primitive part with the desired cylinder colour to your model. This primitive can be added directly to your model (inline primitive) file or placed in a 'custom part' folder. 

As an example - for the `stud2.dat` primitive below, replace the colour code `4242` with `16`, and append the resulting source to your model file.
```
0 Stud Open
0 Name: stud2.dat
0 Author: James Jessiman
0 !LDRAW_ORG Primitive
0 !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
0 BFC CERTIFY CCW
1 16 0 0 0 4 0 0 0 1 0 0 0 4 4-4edge.dat
1 16 0 0 0 6 0 0 0 1 0 0 0 6 4-4edge.dat
1 16 0 -4 0 4 0 0 0 1 0 0 0 4 4-4edge.dat
1 16 0 -4 0 6 0 0 0 1 0 0 0 6 4-4edge.dat
0 BFC INVERTNEXT
0 // to override the high-contrast stud cylinder colour, replace 4242 with your desired colour code
1 4242 0 -4 0 4 0 0 0 4 0 0 0 4 4-4cyli.dat
1 4242 0 -4 0 6 0 0 0 4 0 0 0 6 4-4cyli.dat
1 16 0 -4 0 2 0 0 0 1 0 0 0 2 4-4ring2.dat
```

Be sure _Prefer Official Parts_ is **unchecked** in the Visual Editor Preferences. 

![Stud_Style+01](https://user-images.githubusercontent.com/13388970/232492740-ec0f730b-9534-4aac-b9ef-a1d75d514bd7.png)

If you choose to place the modified stud in a custom folder, be sure the folder is added to the LDraw search paths using the _Configuration_ menu action _LDraw Search Directories..._.

![Stud_Style+02](https://user-images.githubusercontent.com/13388970/232496683-34bcbc98-a89f-4035-85f8-d6b0651d478f.png)

Cheers,

**Comment by technicbasics** [comment]
Thanks for explaining how the code works.
That my solution does not work when both studs and 1/2 pins are present was clear to me.
In my use case I want to adjust the edge colors of the black parts, but leave the studs and pins as they are.
To create this behavior, I will switch back to the 0-PLain setting and adjust the edge color of the black parts in ldconfig.ldr.

Regards Johann

**Comment by technicbasics** [comment]
Have now changed the edge color in ldconfig.ldr and in LDCfgalt.ldr, but this has (unfortunately) no effect. :-(
Which config file does the native renderer access?
As far as I know, the LDView renderer could be tricked that way, or do I remember something wrong?

**Comment by trevorsandy** [comment]
> In my use case I want to adjust the edge colors of the black parts, but leave the studs and pins as they are.

Indeed, if you do not desire the static-coloured studs available by default with high-contrast stud styles, then you will be better served by using an ldconfig file with the desired edge color settings - simply set the alternative ldconfig path in Preferences to an instance with the modified settings.

> Have now changed the edge color in ldconfig.ldr and in LDCfgalt.ldr, but this has (unfortunately) no effect. :-(
Which config file does the native renderer access?

Do not despair, by default, LPub3D uses the ldconfig file in the complete.zip archive library. It is not recommended to change the settings in this file (hence why it is '_hidden_'), instead, simply set you modified ldconfig path as specified above.

![Stud_Style+04](https://user-images.githubusercontent.com/13388970/232574375-75e7b219-db54-48d2-aad3-46f38785954f.png)

Cheers,

**Comment by technicbasics** [comment]
That make sense.
Again thanks.

Regards from Austria

**Comment by technicbasics** [comment]
Hi Trevor
First of all thanks for implementing this feature.
But now the problem, the settings are not saved..
![2023-04-20 21_12_31-Einstellungen](https://user-images.githubusercontent.com/49073781/233465317-920735c9-0b47-4424-b9d6-744de37731d7.png)

after closing the window and reopen..
![2023-04-20 21_13_01-](https://user-images.githubusercontent.com/49073781/233465393-21bed9c1-98bb-4b4d-bd51-e78fee4fe188.png)

It does not matter if a project is open or not, in both cases the settings are not applied.

What code would I need to insert in the Command window to force the settings in the project?

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour.

Making high-contrast stud style colour preferences optional is not yet complete. 

This is why I have not updated this ticket with the new capability - as you can see, it is still in progress. 

Once completed, the behaviour should be as expected.

Cheers,

**Comment by technicbasics** [comment]
Ah... OK.Thank you very much.

**Comment by trevorsandy** [comment]
Making high-contrast stud style colour preferences optional has been completed.

![StudStyleColor](https://user-images.githubusercontent.com/13388970/233651415-7134a5fd-134f-4573-a54f-7318705f62c2.png)

Cheers,
