### ISSUE TITLE
Edge line configuration gets resetted 

### ISSUE THREAD

**Issue by Dark-Noir** [trevorsandy/lpub3d#712]
### Subject
Edge line configuration (for the edge lines of the bricks) is no longer possible. 
The setting can be changed, but it is not applied and is resetted, after re-opening the preferences.
Last working version [2.4.4](https://github.com/trevorsandy/lpub3d/releases/tag/v2.4.4).

### Environment
* Version of LPub3D: 3255 (2.4.6-r144) (fresh *.zip version)
* Operating system: Windows 10 22H2 x64

### Configuration
* Installation path
  - Windows: C:\Users\Darkestnoir\Desktop\Programme\LPub3D
* Configuration
  - Windows (portable): [LPub3D.txt](https://github.com/trevorsandy/lpub3d/files/11525755/LPub3D.txt) (renamed to *.txt)

### Logs
- [LPub3DLog.txt](https://github.com/trevorsandy/lpub3d/files/11525759/LPub3DLog.txt)

### Screenshots
- ![grafik](https://github.com/trevorsandy/lpub3d/assets/8070059/f26ad970-79cd-40cd-a44f-737b80f576e7)

### Preconditions
1. Fresh *.zip extracted

### Steps to reproduce
1. Start LPub3D.exe
2. Select your LDraw lib
3. Go to "Configuration -> Preferences -> Renderers"
5. Set "Edge Lines" to any value greater than 1
6. Close the menu with "OK"
7. Re-open the menu

You can optional load a *.ldr file for testing.

### Expected behavior
- The settings is applied
- The edge lines are thicker

### Actual behavior
- The setting gets resetted in the preference menu to 1
- The edge lines are the same as before

### Workaround
Use a older version, last working one [2.4.4](https://github.com/trevorsandy/lpub3d/releases/tag/v2.4.4).

### Solution suggestion
Fix it and please change the slider to a text field, to enter values directly ^^

**Comment by Dark-Noir** [comment]
Found the a second menu at "Visual Editor -> Preferences" where i can change the configuration and it also gets saved.
Not sure why the same menu is at two locations, but it should be fixed (and also the slider changed to a text field for direct input).

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. 

This behaviour has been corrected.

> Not sure why the same menu is at two locations

The "Visual Editor -> Preferences" dialogue is also present in the LPub3D Preferences window for convenience.

> and also the slider changed to a text field for direct input

LPub3D uses the OpenGL (Open Graphics Library) programming interface (API) to render 3D vector graphics. Line width greater than 1.0 has been deprecated since v3.0, however, while most GPUs support this capability, its implementation must be done in a way to ensure line width values not equal to 1.0 are supported. To this end, it is not a good idea to allow an open  line-width input scheme.

Cheers,
