### ISSUE TITLE
Random crash when saving results in corrupt LDraw file

### ISSUE THREAD

**Issue by jacovandermolen** [trevorsandy/lpub3d#744]
### Subject
Random crash when saving results in corrupt LDraw file

### Environment
* Version of LPub3D x86_64-2.4.7.75.3780_20230905
* Windows 10

### Steps to reproduce
Working on a model and saving the file results in crash. Seemed random at any other given moment or after some editing.
However, I am able to constant reproduce in the case, when opening an LDraw file that has LPub formatting and unformat the document resulting in this dmp file

[LPub3D.dmp](https://github.com/trevorsandy/lpub3d/files/12890842/LPub3D.dmp)

### Expected behaviour
LPub3D should not crash when saving an LDraw file and not corrupt it.

### Actual behaviour
LPub3D crashes when saving a file and corrupts it. It seems the complete file is not written, since it abruptly and randomly ends the file at some random line.

### Workaround
None found.

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
I don't have the binary that generated this dump so the debug analysis is unremarkable. However, I believe #741 to be the part of the source of this behaviour. Additionally, since this behaviour was reported, I have refactored a lot of code for the command editor. With these updates in place, plus those put in place for #767, I am not able to trigger a AbEnd on the latest DevOps build. 

Considering the age of this ticket and the updates state of LPub3D, I'm going to close this ticket. I you experience the behaviour reported in this ticket in the latest DevOps release, do not hesitate to let me know.

Cheers,
