### ISSUE TITLE
Errors on some pages of the instructions

### ISSUE THREAD

**Issue by Draxtax** [trevorsandy/lpub3d#747]
### Subject
LPub3D crashing. Problems are on some pages of the instructions. The page can´t be even shown or can´t be added next step on this page or can´t be added callout on this page.

### Environment
![obrazek](https://github.com/trevorsandy/lpub3d/assets/152692944/e59ba828-4fbf-41d5-ab05-58ba280859de)

### Configuration
[Note: Provide details and content below as needed with appropriate redactions. To produce the Windows registry extract for an installed distribution, go to the command console and enter the command line shown. The extract file will be placed on your desktop.]
* LPub3D installation path
  - Windows: `C:\LPub3D\LPub3D_\LPub3D_x86_64

* Application data path
  - Windows: `C:\Users\lkapi\AppData\Local\LPub3D Software\LPub3D`

* Registry Extract
  - Windows (installed): `reg export "HKEY_CURRENT_USER\Software\LPub3D Software" %USERPROFILE%\Desktop\LPub3D_Hive.reg`
  - Windows (portable): `<application path>\config\LPub3D Software\LPub3D.ini`
[LPub3D_Hive.zip](https://github.com/trevorsandy/lpub3d/files/13538421/LPub3D_Hive.zip)

* Renderer configuration files

[Renderer.zip](https://github.com/trevorsandy/lpub3d/files/13538438/Renderer.zip)

### Logs
* Application Log: `[Application data path]/logs/LPub3DLog.txt`
* Renderer Log: `[LDraw model path]/stdout-ldglite`
* Renderer Log: `[LDraw model path]/stdout-povray`
* Renderer Log: `[LDraw model path]/stderr-ldglite`
* Renderer Log: `[LDraw model path]/stderr-povray`

### Screenshots
* Configuration->Preferences->General
[LPub3D.dmp](https://github.com/trevorsandy/lpub3d/files/13535961/LPub3D.dmp)
[LPub3D.zip](https://github.com/trevorsandy/lpub3d/files/13538406/LPub3D.zip)

![page 10](https://github.com/trevorsandy/lpub3d/assets/152692944/4e8c94ea-d0cb-45f2-bc36-ca0646637535)
![page 220](https://github.com/trevorsandy/lpub3d/assets/152692944/d3d1d199-3944-4335-bc8e-d8463d046276)
![Page 25](https://github.com/trevorsandy/lpub3d/assets/152692944/8e35dbc6-e918-4930-a441-70d433fe2bab)
![page 344](https://github.com/trevorsandy/lpub3d/assets/152692944/0b08cb29-8263-4ef2-b2e7-7b632cd7e11d)
blue marked parts added on this page

* Configuration->Preferences->Rendering
* Configuration->Preferences->Publishing
* Configuration->Preferences->Logging
* Configuration->Preferences->Other

### Steps to reproduce

Main problem - Page 344 error, building instructions can´t be exported to PDF due this error
Page 10 - can´t be added next step on this page
Page 25 - can´t be added next step on this page
Page 220 - Treat As Part error
### Expected behaviour
Tell me what should happen

### Actual behaviour
Tell me what happens instead

### Workaround
[Future JCB 2.zip](https://github.com/trevorsandy/lpub3d/files/13536006/Future.JCB.2.zip)

Share your work around if available

### Solution suggestion
Share your opinion on how to achieve the expected behaviour

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
The behaviour encountered on page 220 has been corrected. See details for your reported items resolution

> Main problem - Page 344 error, building instructions can´t be exported to PDF due this error

This behaviour is a result of the mal-configured _powerFunc2MotorM-1_ submodel.<details>

![MessageCannotWriteToNativePLI-MON](https://github.com/user-attachments/assets/40a5d42b-c28f-44a9-8dbf-4214c53d4c0d)

The `powerFunc2MotorM-1` PLI image cannot be generated because the submodel does not have any fallback LDraw content. Submodel `controlPlusMotorL-LQ-1.ldr` is correctly configured. The excerpt below was taken from the provided _Future JCB 2 - 747.ldr_ LDraw model file.

~~~d
0 FILE powerFunc2MotorM-1.ldr
0 Name: powerFunc2MotorM-1.ldr
0 Author: LDCad
0 !CATEGORY electric
0 !KEYWORDS flexible, power functions 2
0 !LDCAD CONTENT [type=path] [addFallBack=default] [looped=false] [displayKind=mm] [curveStep=0] [displayLenCor=0]
0 !LDCAD PATH_SKIN [donCol=256] [donOri=0 0 1 0 1 0 -1 0 0] [donPart=ldcPwrFuncWire6Seg.dat] [donYSize=400%] [donCen=absCen] [donCenYOfs=0] [donFinScale=fitDon2Seg] [donPlace=deform] [donYAlign=0] [donInline=false] [segSize=100%] [segSizeTol=5%] [segsCnt=0] [segsGrp=0] [segsMaxMerge=10] [segsMrgAng=0] [segsMrgRollAng=0] [segsEdgeDelKind=keepFirstLeft]
0 !LDCAD GENERATED [generator=LDCad 1.7 Beta 1]
0 NOFILE
0
0 FILE controlPlusMotorL-LQ-1.ldr
0 Name: controlPlusMotorL-LQ-1.ldr
0 Author: Philo
0 !CATEGORY electric
0 !KEYWORDS flexible, power functions 2, Powered Up
0 !LDCAD CONTENT [type=path] [addFallBack=default] [looped=false] [displayKind=mm] [curveStep=0] [displayLenCor=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=0 0 141 1 0 0 0 0 1 0 -1 0] [prevCPDist=25] [nextCPDist=23.5] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=0 0 156 1 0 0 0 0 1 0 -1 0] [prevCPDist=25] [nextCPDist=25] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=-5 -44 131 1 0 0 0 0 -1 0 1 0] [prevCPDist=25] [nextCPDist=179.5] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=-40 -20 -109 1 0 0 0 0 -1 0 1 0] [prevCPDist=80.5] [nextCPDist=25] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=-40 -20 -139 1 0 0 0 0 -1 0 1 0] [prevCPDist=25] [nextCPDist=94] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=-135 -76 -119 0 1 0 0 0 1 1 0 0] [prevCPDist=43] [nextCPDist=25] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=-210 -152 -119 0 0 -1 0 1 0 1 0 0] [prevCPDist=54.5] [nextCPDist=25] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=-130 -160 -74 0 -1 0 1 0 0 0 0 1] [prevCPDist=25] [nextCPDist=25] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_POINT [type=bezier] [posOri=-80 -160 -95 1 0 0 0 0 -1 0 1 0] [prevCPDist=30] [nextCPDist=25] [cirR=20] [cirDir=xyCW] [prevYRoll=0] [nextYRoll=0]
0 !LDCAD PATH_SKIN [donCol=256] [donOri=0 0 1 0 1 0 -1 0 0] [donPart=u9218.dat] [donYSize=400%] [donCen=absCen] [donCenYOfs=0] [donFinScale=segMerge] [donPlace=refsStat] [donYAlign=0] [donInline=false] [segSize=50%] [segSizeTol=5%] [segsCnt=0] [segsGrp=0] [segsMaxMerge=1] [segsMrgAng=0] [segsMrgRollAng=0] [segsEdgeDelKind=keepFirstLeft]
0 !LDCAD PATH_CAP [group=start] [color=71] [posOri=0 0 0 1 0 0 0 1 0 0 0 1] [part=22169.dat] [extraLen=0mm] [inlineRef=false]
0 !LDCAD PATH_CAP [group=end] [color=47] [posOri=-80 -160 -109 1 0 0 0 -1 0 0 0 -1] [part=23816a.dat] [extraLen=0mm] [inlineRef=false]
0 !LDCAD PATH_CAP [group=end] [color=256] [posOri=-80 -160 -115 0 0 1 1 0 0 0 20 0] [part=u9218.dat] [extraLen=0mm] [inlineRef=false]
0 !LDCAD GENERATED [generator=LDCad 1.7 Beta 1]
0 //This is the fallback LDraw content for above PATH configuration.
0 // Do not edit, any changes will be lost upon regeneration.
0 // The path is approx 322.78 mm (806.96) and exists out of 403 segments.

0 //Some general hints about the document.
0 UNOFFICIAL PART
0 BFC CERTIFY CCW

0 //Start cap reference(s)
1 71 0 0 0 1 0 0 0 1 0 0 0 1 22169.dat

0 //End cap reference(s)
1 47 -80 -160 -109 1 0 0 0 -1 0 0 0 -1 23816a.dat
1 256 -80 -160 -115 0 0 1 1 0 0 0 20 0 u9218.dat

0 //Fixed color segments
0 //  Skin meta #1 is using a static color.
0 //  To ensure correct edge colors those segments are placed in (a) subpart(s).
1 256 0 0 0 1 0 0 0 1 0 0 0 1 controlPlusMotorL-LQ-1_subPart1.ldr

0 FILE controlPlusMotorL-LQ-1_subPart1.ldr
0 Name: controlPlusMotorL-LQ-1_subPart1.ldr
0 Author: Philo
0 !LDCAD GENERATED [generator=LDCad 1.7 Beta 1] [master=controlPlusMotorL-LQ-1.ldr]
0 //This is additional fallback LDraw content for the "controlPlusMotorL-LQ-1.ldr" PATH configuration.
0 // Do not edit, any changes will be lost upon regeneration.
0 // The path is approx 322.78 mm (806.96) and exists out of 403 segments.

0 //Some general hints about the document.
0 UNOFFICIAL PART
0 BFC CERTIFY CCW

0 //Segments
1 16 0.00099945 0 144.00356224 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 0.00099945 0 146.0083119 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 0.00099945 0 148.01306156 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 0.00099945 0 150.01781122 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 0 0 146.49643776 0 0 0 0 0 0 0 4.00237483 0 u9218.dat
1 16 0 0 145.50118741 0 0 0 0 0 0 0 4.00237483 0 u9218.dat
1 16 0.00099945 0 150.0320602 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 0.00099945 0 152.03680986 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 0.00099945 0 154.04155952 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 0.00099945 0 156.04630918 0 0 1 -1 0 0 0 -4.00237483 0 u9218.dat
1 16 -0.00509534 -0.05363417 158.05035536 0.00001812 0.00812216 0.99999794 -0.99984053 0.07147505 -0.00001812 -0.01785816 -4.00172833 0.00202934 u9218.dat
1 16 -0.04203692 -0.37872083 160.0343336 0 0.05194191 0.99991579 -0.99345617 0.45708882 -0.00148224 -0.11421402 -3.97584911 0.01289285 u9218.dat
1 16 -0.11572291 -1.02716048 161.94363127 0 0.11553418 0.99958328 -0.96716999 1.01670081 -0.00733583 -0.25413029 -3.86936372 0.02791872 u9218.dat
1 16 -0.23789949 -2.10232183 163.66340764 0 0.20142296 0.99873285 -0.89630927 1.77252206 -0.02231597 -0.44342947 -3.58281993 0.04510754 u9218.dat
...
~~~

</details>

> Page 10 - can´t be added next step on this page

I could not generate the message you are reporting on page 10<details>

![NoImagePage10](https://github.com/user-attachments/assets/260d6155-2371-4920-823f-a40e24eb9a7c)

</details>

> Page 25 - can´t be added next step on this page

I could not generate the message you are reporting on page 25<details>

![NoImagePage25](https://github.com/user-attachments/assets/75c9a8f7-f84b-42c5-b2a0-10df92742844)

</details>

> Page 220 - Treat As Part error

This behaviour has been corrected.<details>

This excerpt was taken from the posted _Future JCB 2 - 747.ldr_ LDraw model file.

~~~d
0 FILE subModel-98.ldr
0 Name: subModel-98.ldr
0 Author: LDraw
0 !LPUB MULTI_STEP BEGIN
1 23 0 0 0 1 0 0 0 1 0 0 0 1 6558.dat
1 8 0 0 0 0 -1 0 1 0 0 0 0 1 18654.dat
0 STEP
1 7 20 0 0 0 0 -1 1 0 0 0 -1 0 42003.dat
1 7 -20 0 0 0 0 -1 1 0 0 0 -1 0 42003.dat
1 0 20 20 20 0 0 -1 -1 0 0 0 1 0 18651.dat
1 0 -20 20 20 0 0 -1 -1 0 0 0 1 0 18651.dat
1 7 20 20 20 -1 0 0 0 0 1 0 1 0 3713.dat
1 7 -20 20 20 -1 0 0 0 0 1 0 1 0 3713.dat
0 STEP
1 7 -15 0 -20 -1 0 0 0 0 1 0 1 0 44294.dat
1 8 53 0 -20 0 0 1 1 0 0 0 1 0 59443.dat
0 !LPUB PLI BEGIN SUB subModel-21.ldr 7
0 !LPUB PART BEGIN IGN
1 7 -95 0 -20 0 0 1 1 0 0 0 1 0 subModel-21.ldr
0 !LPUB PLI END
0 !LPUB PART END
1 7 -127.848 9.947 -40.544 -0.821 -0.531 0.21 0.249 -0.002 0.969 -0.514 0.848 0.134 4519.dat
1 7 -160.696 19.895 -61.088 -0.21 0.531 0.821 -0.969 0.002 -0.249 -0.134 -0.848 0.514 subModel-21.ldr
0 STEP
0 !LPUB MULTI_STEP END
0 NOFILE
~~~

It is not common or intuitive to substitute a part with itself. Moreover, this substitute part is a submodel. A better solution is to use substitute your submodel with Universal joint `61903.dat`.
![TreatAsPart_1](https://github.com/user-attachments/assets/f2acdebe-ae2a-4d38-ae8d-d59a9c9e8009)

Nevertheless, I have updated the behaviour to resolve this scenario.
![TreatAsPart_2](https://github.com/user-attachments/assets/7eb3cf09-3824-4947-8231-8a20b7b4aaaa)

The expected output
![TreatAsPart_3](https://github.com/user-attachments/assets/f5229285-d063-484f-b9ce-7f69b86a71af)

</details>

Cheers,
