### ISSUE TITLE
LDV Render Preferences

### ISSUE THREAD

**Issue by LassesLego** [trevorsandy/lpub3d#787]
**Summary**

After installing LPub3D 2.4.8.0.3723 (Which solved my issue 742. Thank you!) and selecting renderer LDview, the program crashes when I select LDview Preferences.

**LPub3D Version**

  - Incarnation: Downloaded zip file, unzipped and moved to user directory
  - Affected build version: 2.4.8.0.3723
  - Known working build version: 2.4.7.75.3551

**Runtime Environment**

  - Operating system: Windows 11 Home 23H2
  - Hardware architecture: 64 bit
  - CPU model: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz   2.90 GHz

**Steps to Reproduce**

 1. Configuration
 2. Preferences
 3. Renderers
 4. LDView
 5. LDView Preferences
 6. Crash

**Output or example Input**<details>
[LPub3D.dmp](https://github.com/user-attachments/files/17732116/LPub3D.dmp)

**Comment by DanieleBenedettelli** [comment]
Same problem here. I'm following this

Il mer 13 nov 2024, 13:14 LassesLego ***@***.***> ha scritto:

**Comment by trevorsandy** [comment]
After further investigation, I discovered this behaviour is not related to #773. 

Instead it is because of the new zip support capability in LDView (tcobbs/ldview@18784e8) which was incorporated into LPub3D LDV in commit cc374b351e45a6. In summary, LPub3D uses _QuaZip_ while LDView now uses _minizip_. This causes LPub3D to violate the _One Definition Rule_ as _QuaZip_ is essentially a wrapper for _minizip_. 

In the case for the reported behaviour, the LDV module is attempting to access the _minizip_ instance of `zopen64` but is linked to the _QuaZip_ instance. This situation causes an immediate AbEnd when attempting to open the LDV Preferences dialog. 

The rather _hacky_ treatment is to have LPub3D link the LDV/_minizip_ module before linking _QuaZip_ and include the linking flag [/FORCE:MULTIPLE](https://learn.microsoft.com/en-us/cpp/build/reference/force-force-file-output?view=msvc-170) for MSVC builds.

Cheers,

**Comment by trevorsandy** [comment]
This behaviour has been corrected.

![LDV Render](https://github.com/user-attachments/assets/63cf4977-b283-41c2-9e5f-c02bcaf1a0f8)

Cheers,
