### ISSUE TITLE
LPub3D crashes unexpectedly and sporadically

### ISSUE THREAD

**Issue by technicbasics** [trevorsandy/lpub3d#788]
The problem occurs either during or at the end of the export process. (I have only exported to .png so far.) But the problem has also occurred when quickly scrolling through the instructions.
Renderer used: Native
Stud style: 6 - High Contrast
Stud Cylinder Color disabled

![grafik](https://github.com/user-attachments/assets/f870b255-fa1e-4815-9bca-98448ee96d4d)

**LPub3D Version**

  - Incarnation: Windows portable in admin mode
  - Affected build version:  2.4.8r105
  - Known working build version: 2.4.8r0

**Runtime Environment**

  - Operating system: 
  - Windows 11 Home Version 24H2

  - Hardware architecture:
Prozessor	11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz   2.50 GHz
Installierter RAM	16,0 GB (15,8 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

Error file after exporting:
[LPub3D_2024_11_12a.zip](https://github.com/user-attachments/files/17738069/LPub3D_2024_11_12a.zip)

Error file after scrolling
[LPub3D_2024_11_13.zip](https://github.com/user-attachments/files/17738075/LPub3D_2024_11_13.zip)

**Comment by trevorsandy** [comment]
Thank you for reporting this behaviour. I'll take a look.

Cheers,

**Comment by trevorsandy** [comment]
Can you post a zipped copy of LPub3D.exe for r105 - this revision no longer exists and I need it to debug the .dmp file - Thanks.

Cheers,

**Comment by technicbasics** [comment]
[LPub3D_1.zip](https://github.com/user-attachments/files/17744970/LPub3D_1.zip)

Unfortunately, the latest version r110 is only available for Mac, otherwise I would have tested it too.

**Comment by trevorsandy** [comment]
I was able to reproduce this behaviour with a fresh release build. 

The cause is several performance enhancements I put in place to enable the UI to be more responsive when handling large files (over 200K lines) like your shared example. Unfortunately, as the native renderer engine also doubles as the visual editor engine, it does not take well to being clobbered by process events signals. 

Anyway, I've removed the enhancements that were implicated - which is most of them so the UI responsiveness will be a bit sluggish on large file processing - particularly if you elect to load the entire model at cover page display. There are still some enhacements in place, so you can evaluate this change in the latest [DevOps](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) build and let me know if you continue to experience this behavoiur. The enhancements remain in place around file Load, BuildMod, Fade and Highlight routines so, except for Load, it would be good to test in these areas.

> Unfortunately, the latest version r110 is only available for Mac

The DevOps build I triggered this morning is a full build except for the arm/qemu stuff.

Cheers,

**Comment by technicbasics** [comment]
The funny thing is that the program doesn't always crash at the same point or during the same process, but rather sporadically. Is the change in r110 from this morning already included?

**Comment by technicbasics** [comment]
I forgot to mention that the file used only has approx. 8200 lines. I can also make it available to you.

**Comment by trevorsandy** [comment]
> Is the change in r110 from this morning already included?

Yes. 

Cheers,

**Comment by technicbasics** [comment]
Many thanks, I will try it asap.
And of course I meant r141.

**Comment by technicbasics** [comment]
I have just exported my new model with version r157
1st attempt crashed after page 67 (end model 1)
2nd attempt crashed at the end of the complete model
3rd attempt ran without problems

If you need the model file, let me know.

[LPub3D.zip](https://github.com/user-attachments/files/17786718/LPub3D.zip)
[LPub3D_exe.zip](https://github.com/user-attachments/files/17786723/LPub3D_exe.zip)

**Comment by trevorsandy** [comment]
Many thanks. I'll take a look. 

Cheers,

**Comment by trevorsandy** [comment]
While the source of the AbEnd is the same as the other AbEnds, the trigger is different. This is to say the 'concurrent processing enhancements' I referred to above are not the cause of the AbEnd according to the stack captured in the dmp file. 

I ran a 225-step LDraw example on 'Continuous next page processing' and no AbEnd was triggered.

I'll produce a build without the enhancements that run during page processing. This way we can rule out up-or-down that this behaviour is caused by the enhancements.

Cheers,

**Comment by technicbasics** [comment]
Many thanks for your work.
I will send you my latest file via Wetransfer, then you have two different files.

Regards Johann

**Comment by trevorsandy** [comment]
I've reversed the last of the performance enhancements that were causing this behaviour. 

You can evaluate this and other corrections in the latest [DevOps](https://github.com/trevorsandy/lpub3d-ci/releases/tag/continuous) build.

Cheers,
