### ISSUE TITLE
LPub3D LDView preferences dialog is incomplete

### ISSUE THREAD

**Issue by Landcross** [trevorsandy/lpub3d#97]
I just updated to LPub3D and it contains some cool features and enhancements. However, I also noticed a big downgrade in render-quality, which is something I didn't like to see since I'm in the midst of working on a project.

Then I noticed that LPub3D now has a LDView render preferences dialog of its own instead of using the one from within LDView itself. I have no idea why there is a need for that, but I don't really mind as long as they are the same. Which they are not...

So far, I found a two settings I have setup in my real LDView preferences which I can't setup in LPub3D's LDView preferences.

**Tab General**
- FSAA has only 2 options in LPub3D while it has 7 options in LDView. I specifically want to use FSAA x16 which is also not listed in LPub3D.
- Field of view can include a decimal point in LDView, but in LPub3D it has to be an integer. I specificially want to use a field of view of 0.1 (which is the lowest LDView can go), but the lowest I can select in LPub3D is 1.

Furthermore, it seems changing the settings have no effect at all anyway, but I'll create a separate issue for that in a moment.

**Comment by trevorsandy** [comment]
Thanks for sharing your thoughts. It is completely understandable that you are puzzled about the new interface options because I have not yet updated the ticket for this ,and other, new features that would help you in this regard. If you experience a reduction of render quality, you should take a look at the configuration options in LPub3D - i.e. LDView, LDGLite ini files.

Having said that, LPub3D has it's own LDView parameter management UI for two reasons:

1 - LPub3D uses its own slightly customized instance of LDView which, except on Windows, is a console only instance. This means no user interface for the user to immediately access. Moreover, accessing the LPub3D instance of LDView is not immediately accessible to the average end user on Windows, where the LPub3D LDView instance does still have a GUI. The purpose of the GUI is to facilitate updating the LDView.ini file presenting a familiar interface experience for LDView users.

2 - LPub3D uses the LDView classes, as they are compiled during LPub3D build, to manage the new "Native" POV-File generation (in addition to LDView's own POV file generation) which is part of an ongoing effort to bring enhanced capabilities to LPub3D including image matting and such. As I initially enabled, the interface to enable this interaction. I simply extended the work to also manipulate the LDView.ini files

So now you have 2 "Ideas" why I implemented this capability. 

Keep in mind the purpose of LPub3D's LDView focused, at the moment, on snapshot and POV generation, so UI-related options are not interesting for me to implement.

To address your unexpected LPub3D behaviour in the most efficient manner, it's better add some screenshots with your descriptions which is quite simple to do with GitHub. I interpret your message to suggest you are expecting the LPub3D LDView parameter dialogue to update your non-LPub3D instance of LDView. If my interpretation is correct, then be advised that this is not a capability in LPub3D.

Lastly, there is the option to directly edit the LDView.ini parameter, this is what the UI interface actually updates. Nevertheless, please do continue to report your experience - unpleasant or pleasant. 

Cheers,

**Comment by Landcross** [comment]
Thanks for the thorough explanation Trevor, I appreciate that.

> I interpret your message to suggest you are expecting the LPub3D LDView parameter dialogue to update your non-LPub3D instance of LDView. If my interpretation is correct, then be advised that this is not a capability in LPub3D.

Certainly not. I don't expect LPub3D's LDView preferences dialog to update my standalone LDView's settings. There are a few settings (which I listed above) in LDView's own preference dialog that are not available in LPub3D's LDView dialog.

I guess some images say more than a 1000 words:

**Anti-Aliasing**
LDView:
![image](https://user-images.githubusercontent.com/12005521/45512385-e2f21880-b79f-11e8-93ea-34806df4cf2e.png)

LPub3D:
![image](https://user-images.githubusercontent.com/12005521/45512443-02894100-b7a0-11e8-8b1c-fd673a99b075.png)



**Field of view**
LDView:
![image](https://user-images.githubusercontent.com/12005521/45512478-1c2a8880-b7a0-11e8-9291-21d43457c321.png)

LPub3D:
![image](https://user-images.githubusercontent.com/12005521/45512502-25b3f080-b7a0-11e8-8dd3-2e22f1ca834e.png)

**Comment by trevorsandy** [comment]
Excellent - these are quite easy to update. I'll take a look. By the way, version 2.3.1 is imminent. You can see the issue list (filter 2.3.1) of the included updates and fixes.

Cheers,

**Comment by trevorsandy** [comment]
I can't seem to find the version of LDView you are referencing. 

While I can certainly address the decimal on the spinner, I don't know where to find the instance of LDView supporting the range of Anti-Aliasing options you are showing in your shots.

Here is the latest I have...

Installed instance:
![screenshot - 13_09_2018 22_32_56](https://user-images.githubusercontent.com/13388970/45514776-a1b13700-b7a6-11e8-9cb6-4aeb8e0cd410.png)

![screenshot - 13_09_2018 22_33_16](https://user-images.githubusercontent.com/13388970/45514789-a83fae80-b7a6-11e8-8184-9358a4f2077d.png)


LPub3D built instance - Windows
![screenshot - 13_09_2018 22_40_42](https://user-images.githubusercontent.com/13388970/45514816-b988bb00-b7a6-11e8-8921-92b2788a74e4.png)

![screenshot - 13_09_2018 22_40_58](https://user-images.githubusercontent.com/13388970/45514821-bdb4d880-b7a6-11e8-8fe6-a18fe0721099.png)

Cheers,

**Comment by Landcross** [comment]
Hmm, seems I have an older LDView installed on my machine:
![image](https://user-images.githubusercontent.com/12005521/45535163-da302f80-b7fd-11e8-816d-7d6282cad755.png)

**Comment by trevorsandy** [comment]
Corrected.

![screenshot - 15_09_2018 00_13_00](https://user-images.githubusercontent.com/13388970/45577449-4782a580-b87c-11e8-9b83-9ad2097358f2.png)

Cheers,
